/****************************Inserts Countrys**********************************/
/*******************************America****************************************/
insert into Country(nameCountry) values ('Argentina');
insert into Country(nameCountry) values ('Bolivia');
insert into Country(nameCountry) values ('Canadá');
insert into Country(nameCountry) values ('Colombia');
insert into Country(nameCountry) values ('Cuba');
insert into Country(nameCountry) values ('Ecuador');
insert into Country(nameCountry) values ('Guatemala');
insert into Country(nameCountry) values ('Haití');
insert into Country(nameCountry) values ('Jamaica');
insert into Country(nameCountry) values ('Nicaragua');
insert into Country(nameCountry) values ('Paraguay');
insert into Country(nameCountry) values ('Surinam');
insert into Country(nameCountry) values ('Uruguay');
insert into Country(nameCountry) values ('Belice');
insert into Country(nameCountry) values ('Brasil');
insert into Country(nameCountry) values ('Chile');
insert into Country(nameCountry) values ('República Dominicana');
insert into Country(nameCountry) values ('El Salvador');
insert into Country(nameCountry) values ('Guyana');
insert into Country(nameCountry) values ('Honduras');
insert into Country(nameCountry) values ('México');
insert into Country(nameCountry) values ('Panamá');
insert into Country(nameCountry) values ('Perú');
insert into Country(nameCountry) values ('Estados Unidos');
insert into Country(nameCountry) values ('Venezuela');

/**************************************Europe**********************************/
insert into Country(nameCountry) values ('Albania');
insert into Country(nameCountry) values ('Austria');
insert into Country(nameCountry) values ('Bosnia y Herzogovina');
insert into Country(nameCountry) values ('Croacia');
insert into Country(nameCountry) values ('Dinamarca');
insert into Country(nameCountry) values ('Francia');
insert into Country(nameCountry) values ('Grecia');
insert into Country(nameCountry) values ('Hungría');
insert into Country(nameCountry) values ('Irlanda');
insert into Country(nameCountry) values ('Letonia');
insert into Country(nameCountry) values ('Lituania');
insert into Country(nameCountry) values ('Macedonia del Norte');
insert into Country(nameCountry) values ('Mónaco');
insert into Country(nameCountry) values ('Noruega');
insert into Country(nameCountry) values ('Portugal');
insert into Country(nameCountry) values ('Rusia');
insert into Country(nameCountry) values ('Eslovaquia');
insert into Country(nameCountry) values ('España');
insert into Country(nameCountry) values ('Suiza');
insert into Country(nameCountry) values ('Estonia');
insert into Country(nameCountry) values ('Montenegro');
insert into Country(nameCountry) values ('Andorra');
insert into Country(nameCountry) values ('Bélgica');
insert into Country(nameCountry) values ('Bulgaria');
insert into Country(nameCountry) values ('Chequia');
insert into Country(nameCountry) values ('Finlandia');
insert into Country(nameCountry) values ('Alemania');
insert into Country(nameCountry) values ('Ciudad del Vaticano');
insert into Country(nameCountry) values ('Islandia');
insert into Country(nameCountry) values ('Italia');
insert into Country(nameCountry) values ('Liechtenstein');
insert into Country(nameCountry) values ('Luxemburgo');
insert into Country(nameCountry) values ('Malta');
insert into Country(nameCountry) values ('Países Bajos');
insert into Country(nameCountry) values ('Polonia');
insert into Country(nameCountry) values ('Rumania');
insert into Country(nameCountry) values ('San Marino');
insert into Country(nameCountry) values ('Eslovenia');
insert into Country(nameCountry) values ('Suecia');
insert into Country(nameCountry) values ('Inglaterra');
insert into Country(nameCountry) values ('Gales');
insert into Country(nameCountry) values ('Escocia');
insert into Country(nameCountry) values ('Serbia');
/******************************America news************************************/
insert into Country(nameCountry) values ('Costa Rica');
insert into Country(nameCountry) values ('Antigua y Barbuda');
insert into Country(nameCountry) values ('Bahamas');
insert into Country(nameCountry) values ('Barbados');
insert into Country(nameCountry) values ('Dominica');
insert into Country(nameCountry) values ('Granada');
insert into Country(nameCountry) values ('San Cristóbal y Nieves');
insert into Country(nameCountry) values ('San Vicente y las Granadinas');
insert into Country(nameCountry) values ('Santa Lucía');
insert into Country(nameCountry) values ('Trinidad y Tobago');
/******************************Europa news*************************************/
insert into Country(nameCountry) values ('Turquía');
insert into Country(nameCountry) values ('Bielorrusia');
insert into Country(nameCountry) values ('Chipre');
insert into Country(nameCountry) values ('Georgia');
insert into Country(nameCountry) values ('Moldavia');
insert into Country(nameCountry) values ('Ucrania');

/**************************************Asia************************************/
insert into Country(nameCountry) values ('Afganistán');
insert into Country(nameCountry) values ('Arabia Saudita');
insert into Country(nameCountry) values ('Armenia');
insert into Country(nameCountry) values ('Azerbaiyán');
insert into Country(nameCountry) values ('Bangladés');
insert into Country(nameCountry) values ('Baréin');
insert into Country(nameCountry) values ('Birmania');
insert into Country(nameCountry) values ('Brunéi');
insert into Country(nameCountry) values ('Bután');
insert into Country(nameCountry) values ('Camboya');
insert into Country(nameCountry) values ('Catar');
insert into Country(nameCountry) values ('China');
insert into Country(nameCountry) values ('Corea del Norte');
insert into Country(nameCountry) values ('Emiratos Árabes Unidos');
insert into Country(nameCountry) values ('Filipinas');
insert into Country(nameCountry) values ('India');
insert into Country(nameCountry) values ('Indonesia');
insert into Country(nameCountry) values ('Irak');
insert into Country(nameCountry) values ('Irán');
insert into Country(nameCountry) values ('Israel');
insert into Country(nameCountry) values ('Japón');
insert into Country(nameCountry) values ('Jordania');
insert into Country(nameCountry) values ('Kazajistán');
insert into Country(nameCountry) values ('Kirguistán');
insert into Country(nameCountry) values ('Kuwait');
insert into Country(nameCountry) values ('Laos');
insert into Country(nameCountry) values ('Líbano');
insert into Country(nameCountry) values ('Malasia');
insert into Country(nameCountry) values ('Maldivas');
insert into Country(nameCountry) values ('Mongolia');
insert into Country(nameCountry) values ('Nepal');
insert into Country(nameCountry) values ('Omán');
insert into Country(nameCountry) values ('Pakistán');
insert into Country(nameCountry) values ('Singapur');
insert into Country(nameCountry) values ('Siria');
insert into Country(nameCountry) values ('Sri Lanka');
insert into Country(nameCountry) values ('Tailandia');
insert into Country(nameCountry) values ('Tayikistán');
insert into Country(nameCountry) values ('Timor Oriental');
insert into Country(nameCountry) values ('Turkmenistán');
insert into Country(nameCountry) values ('Uzbekistán');
insert into Country(nameCountry) values ('Vietnam');
insert into Country(nameCountry) values ('Yemen');

/**************************************Oceania*********************************/

insert into Country(nameCountry) values ('Australia');
insert into Country(nameCountry) values ('Fiyi');
insert into Country(nameCountry) values ('Islas Marshall');
insert into Country(nameCountry) values ('Islas Salomón');
insert into Country(nameCountry) values ('Kiribati');
insert into Country(nameCountry) values ('Micronesia');
insert into Country(nameCountry) values ('Nauru');
insert into Country(nameCountry) values ('Nueva Zelanda');
insert into Country(nameCountry) values ('Palaos');
insert into Country(nameCountry) values ('Papúa Nueva Guinea');
insert into Country(nameCountry) values ('Samoa');
insert into Country(nameCountry) values ('Tonga');
insert into Country(nameCountry) values ('Tuvalu');
insert into Country(nameCountry) values ('Vanuatu');

/************************************Africa************************************/
insert into Country(nameCountry) values ('Angola');
insert into Country(nameCountry) values ('Argelia');
insert into Country(nameCountry) values ('Benín');
insert into Country(nameCountry) values ('Botsuana');
insert into Country(nameCountry) values ('Burkina Faso');
insert into Country(nameCountry) values ('Burundi');
insert into Country(nameCountry) values ('Cabo Verde');
insert into Country(nameCountry) values ('Camerún');
insert into Country(nameCountry) values ('Chad');
insert into Country(nameCountry) values ('Comoras');
insert into Country(nameCountry) values ('Costa de Marfil');
insert into Country(nameCountry) values ('Egipto');
insert into Country(nameCountry) values ('Eritrea');
insert into Country(nameCountry) values ('Etiopía');
insert into Country(nameCountry) values ('Gabón');
insert into Country(nameCountry) values ('Gambia');
insert into Country(nameCountry) values ('Ghana');
insert into Country(nameCountry) values ('Guinea');
insert into Country(nameCountry) values ('Guinea-Bisáu');
insert into Country(nameCountry) values ('Guinea Ecuatorial');
insert into Country(nameCountry) values ('Kenia');
insert into Country(nameCountry) values ('Lesoto');
insert into Country(nameCountry) values ('Liberia');
insert into Country(nameCountry) values ('Libia');
insert into Country(nameCountry) values ('Madagascar');
insert into Country(nameCountry) values ('Malaui');
insert into Country(nameCountry) values ('Malí');
insert into Country(nameCountry) values ('Marruecos');
insert into Country(nameCountry) values ('Mauricio');
insert into Country(nameCountry) values ('Mauritania');
insert into Country(nameCountry) values ('Mozambique');
insert into Country(nameCountry) values ('Namibia');
insert into Country(nameCountry) values ('Níger');
insert into Country(nameCountry) values ('Nigeria');
insert into Country(nameCountry) values ('República Centroafricana');
insert into Country(nameCountry) values ('República del Congo');
insert into Country(nameCountry) values ('República Democrática del Congo');
insert into Country(nameCountry) values ('Ruanda');
insert into Country(nameCountry) values ('Santo Tomé y Príncipe');
insert into Country(nameCountry) values ('Senegal');
insert into Country(nameCountry) values ('Seychelles');
insert into Country(nameCountry) values ('Sierra Leona');
insert into Country(nameCountry) values ('Somalia');
insert into Country(nameCountry) values ('Suazilandia');
insert into Country(nameCountry) values ('Sudáfrica');
insert into Country(nameCountry) values ('Sudán');
insert into Country(nameCountry) values ('Sudán del Sur');
insert into Country(nameCountry) values ('Tanzania');
insert into Country(nameCountry) values ('Togo');
insert into Country(nameCountry) values ('Túnez');
insert into Country(nameCountry) values ('Uganda');
insert into Country(nameCountry) values ('Yibuti');
insert into Country(nameCountry) values ('Zambia');
insert into Country(nameCountry) values ('Zimbabue');


insert into Country(nameCountry) values ('Corea del Sur');
/*******************************Insert provinces*******************************/
/******************************************************************************/
/*---Costa Rica*/
insert into City(idCountry, nameCity) values (69, 'San José');
insert into City(idCountry, nameCity) values (69, 'Limón');
insert into City(idCountry, nameCity) values (69, 'Cartago');
insert into City(idCountry, nameCity) values (69, 'Puntarenas');
insert into City(idCountry, nameCity) values (69, 'Heredia');
insert into City(idCountry, nameCity) values (69, 'Alajuela');
insert into City(idCountry, nameCity) values (69, 'Guanacaste');
---Argentina
insert into City(idCountry, nameCity) values (1, 'Buenos Aires');
insert into City(idCountry, nameCity) values (1, 'Chubut');
insert into City(idCountry, nameCity) values (1, 'Corrientes');
insert into City(idCountry, nameCity) values (1, 'Jujuy');
insert into City(idCountry, nameCity) values (1, 'Mendoza');
insert into City(idCountry, nameCity) values (1, 'Río Negro');
insert into City(idCountry, nameCity) values (1, 'San Luis');
insert into City(idCountry, nameCity) values (1, 'Santiago del Estero');
insert into City(idCountry, nameCity) values (1, 'Catamarca');
insert into City(idCountry, nameCity) values (1, 'Entre Ríos');
insert into City(idCountry, nameCity) values (1, 'La Pampa');
insert into City(idCountry, nameCity) values (1, 'Misiones');
insert into City(idCountry, nameCity) values (1, 'Salta');
insert into City(idCountry, nameCity) values (1, 'Santa Cruz');
insert into City(idCountry, nameCity) values (1, 'Chaco');
insert into City(idCountry, nameCity) values (1, 'Córdoba');
insert into City(idCountry, nameCity) values (1, 'Formosa');
insert into City(idCountry, nameCity) values (1, 'La Rioja');
insert into City(idCountry, nameCity) values (1, 'Neuquén');
insert into City(idCountry, nameCity) values (1, 'San Juan');
insert into City(idCountry, nameCity) values (1, 'Santa Fe');
insert into City(idCountry, nameCity) values (1, 'Tucumán');
insert into City(idCountry, nameCity) values (1, 'Tierra del Fuego, Antártida e Islas del Atlántico Sur');
---Bolivia
insert into City(idCountry, nameCity) values (2, 'Beni');
insert into City(idCountry, nameCity) values (2, 'La Paz');
insert into City(idCountry, nameCity) values (2, 'Potosí');
insert into City(idCountry, nameCity) values (2, 'Chuquisaca');
insert into City(idCountry, nameCity) values (2, 'Oruro');
insert into City(idCountry, nameCity) values (2, 'Santa Cruz');
insert into City(idCountry, nameCity) values (2, 'Cochobamba');
insert into City(idCountry, nameCity) values (2, 'Pando');
insert into City(idCountry, nameCity) values (2, 'Tarija');
---Canadá
insert into City(idCountry, nameCity) values (3, 'Alberta');
insert into City(idCountry, nameCity) values (3, 'Manitoba');
insert into City(idCountry, nameCity) values (3, 'Nunavut');
insert into City(idCountry, nameCity) values (3, 'Saskatchewan');
insert into City(idCountry, nameCity) values (3, 'Yukón');
insert into City(idCountry, nameCity) values (3, 'Columbia Británica');
insert into City(idCountry, nameCity) values (3, 'Nuevo Brunswick');
insert into City(idCountry, nameCity) values (3, 'Ontario');
insert into City(idCountry, nameCity) values (3, 'Terranova y Labrador');
insert into City(idCountry, nameCity) values (3, 'Isla del Príncipe Eduardo');
insert into City(idCountry, nameCity) values (3, 'Nueva Escocia');
insert into City(idCountry, nameCity) values (3, 'Quebec');
insert into City(idCountry, nameCity) values (3, 'Territorios del Noroeste');
---Colombia
insert into City(idCountry, nameCity) values (4, 'Amazonas');
insert into City(idCountry, nameCity) values (4, 'Atlántico');
insert into City(idCountry, nameCity) values (4, 'Caldas');
insert into City(idCountry, nameCity) values (4, 'Cauca');
insert into City(idCountry, nameCity) values (4, 'Córdoba');
insert into City(idCountry, nameCity) values (4, 'Guaviare');
insert into City(idCountry, nameCity) values (4, 'Magdalena');
insert into City(idCountry, nameCity) values (4, 'Norte de Santander');
insert into City(idCountry, nameCity) values (4, 'Risaralda');
insert into City(idCountry, nameCity) values (4, 'Sucre');
insert into City(idCountry, nameCity) values (4, 'Vaupés');
insert into City(idCountry, nameCity) values (4, 'Antioquia');
insert into City(idCountry, nameCity) values (4, 'Bolívar');
insert into City(idCountry, nameCity) values (4, 'Caquetá');
insert into City(idCountry, nameCity) values (4, 'Cesar');
insert into City(idCountry, nameCity) values (4, 'Cundinamarca');
insert into City(idCountry, nameCity) values (4, 'Huila');
insert into City(idCountry, nameCity) values (4, 'Meta');
insert into City(idCountry, nameCity) values (4, 'Putumayo');
insert into City(idCountry, nameCity) values (4, 'Archipiélago de San Andrés');
insert into City(idCountry, nameCity) values (4, 'Tolima');
insert into City(idCountry, nameCity) values (4, 'Vichada');
insert into City(idCountry, nameCity) values (4, 'Arauca');
insert into City(idCountry, nameCity) values (4, 'Boyacá');
insert into City(idCountry, nameCity) values (4, 'Casanare');
insert into City(idCountry, nameCity) values (4, 'Chocó');
insert into City(idCountry, nameCity) values (4, 'Guainía');
insert into City(idCountry, nameCity) values (4, 'La Guajira');
insert into City(idCountry, nameCity) values (4, 'Nariño');
insert into City(idCountry, nameCity) values (4, 'Quindío');
insert into City(idCountry, nameCity) values (4, 'Santander');
insert into City(idCountry, nameCity) values (4, 'Valle Del Cauca');
---Cuba
insert into City(idCountry, nameCity) values (5, 'Artemisa');
insert into City(idCountry, nameCity) values (5, 'Cienfuegos');
insert into City(idCountry, nameCity) values (5, 'Holguín');
insert into City(idCountry, nameCity) values (5, 'Las Tunas');
insert into City(idCountry, nameCity) values (5, 'Pinar del Río');
insert into City(idCountry, nameCity) values (5, 'Villa Clara');
insert into City(idCountry, nameCity) values (5, 'Camagüey');
insert into City(idCountry, nameCity) values (5, 'Granma');
insert into City(idCountry, nameCity) values (5, 'Isla de la Juventud');
insert into City(idCountry, nameCity) values (5, 'Matanzas');
insert into City(idCountry, nameCity) values (5, 'Sancti Spíritus');
insert into City(idCountry, nameCity) values (5, 'Ciego de Ávila');
insert into City(idCountry, nameCity) values (5, 'Guantánamo');
insert into City(idCountry, nameCity) values (5, 'La Habana');
insert into City(idCountry, nameCity) values (5, 'Mayabeque');
insert into City(idCountry, nameCity) values (5, 'Santiago de Cuba');
---Ecuador
insert into City(idCountry, nameCity) values (6, 'Azuay');
insert into City(idCountry, nameCity) values (6, 'Bolívar');
insert into City(idCountry, nameCity) values (6, 'Cañar');
insert into City(idCountry, nameCity) values (6, 'Carchi');
insert into City(idCountry, nameCity) values (6, 'Chimborazo');
insert into City(idCountry, nameCity) values (6, 'Cotopaxi');
insert into City(idCountry, nameCity) values (6, 'El Oro');
insert into City(idCountry, nameCity) values (6, 'Esmeraldas');
insert into City(idCountry, nameCity) values (6, 'Galápagos');
insert into City(idCountry, nameCity) values (6, 'Guayas');
insert into City(idCountry, nameCity) values (6, 'Imbabura');
insert into City(idCountry, nameCity) values (6, 'Loja');
insert into City(idCountry, nameCity) values (6, 'Los Ríos');
insert into City(idCountry, nameCity) values (6, 'Manabí');
insert into City(idCountry, nameCity) values (6, 'Morona Santiago');
insert into City(idCountry, nameCity) values (6, 'Napo');
insert into City(idCountry, nameCity) values (6, 'Orellana');
insert into City(idCountry, nameCity) values (6, 'Pastaza');
insert into City(idCountry, nameCity) values (6, 'Pichincha');
insert into City(idCountry, nameCity) values (6, 'Santa Elena');
insert into City(idCountry, nameCity) values (6, 'Santo Domingo de los Tsáchilas');
insert into City(idCountry, nameCity) values (6, 'Sucumbíos');
insert into City(idCountry, nameCity) values (6, 'Tungurahua');
insert into City(idCountry, nameCity) values (6, 'Zamora Chinchipe');
---Guatemala
insert into City(idCountry, nameCity) values (7, 'Guatemala');
insert into City(idCountry, nameCity) values (7, 'Baja Verapaz');
insert into City(idCountry, nameCity) values (7, 'Alta Verapaz');
insert into City(idCountry, nameCity) values (7, 'El Progreso');
insert into City(idCountry, nameCity) values (7, 'Izabal');
insert into City(idCountry, nameCity) values (7, 'Zacapa');
insert into City(idCountry, nameCity) values (7, 'Chiquimula');
insert into City(idCountry, nameCity) values (7, 'Jalapa');
insert into City(idCountry, nameCity) values (7, 'Jutiapa');
insert into City(idCountry, nameCity) values (7, 'Santa Rosa');
insert into City(idCountry, nameCity) values (7, 'Sololá');
insert into City(idCountry, nameCity) values (7, 'Totonicapán');
insert into City(idCountry, nameCity) values (7, 'Quetzaltenango');
insert into City(idCountry, nameCity) values (7, 'Suchitepéquez');
insert into City(idCountry, nameCity) values (7, 'Retalhuleu');
insert into City(idCountry, nameCity) values (7, 'San Marcos');
insert into City(idCountry, nameCity) values (7, 'Huehuetenango');
insert into City(idCountry, nameCity) values (7, 'Quiché');
insert into City(idCountry, nameCity) values (7, 'Escuintla');
insert into City(idCountry, nameCity) values (7, 'Sacatepéquez');
insert into City(idCountry, nameCity) values (7, 'Chimaltenango');
insert into City(idCountry, nameCity) values (7, 'Petén');
---Haití
insert into City(idCountry, nameCity) values (8, 'Artibonite');
insert into City(idCountry, nameCity) values (8, 'Centro');
insert into City(idCountry, nameCity) values (8, 'Grand Anse');
insert into City(idCountry, nameCity) values (8, 'Nippes');
insert into City(idCountry, nameCity) values (8, 'Norte');
insert into City(idCountry, nameCity) values (8, 'Nordeste');
insert into City(idCountry, nameCity) values (8, 'Noroeste');
insert into City(idCountry, nameCity) values (8, 'Oeste');
insert into City(idCountry, nameCity) values (8, 'Sur');
insert into City(idCountry, nameCity) values (8, 'Sudeste');
---Jamaica
insert into City(idCountry, nameCity) values (9, 'Clarendon');
insert into City(idCountry, nameCity) values (9, 'Hanover');
insert into City(idCountry, nameCity) values (9, 'Kingston');
insert into City(idCountry, nameCity) values (9, 'Manchester');
insert into City(idCountry, nameCity) values (9, 'Portland');
insert into City(idCountry, nameCity) values (9, 'Saint Andrew');
insert into City(idCountry, nameCity) values (9, 'Saint Ann');
insert into City(idCountry, nameCity) values (9, 'Saint Catherine');
insert into City(idCountry, nameCity) values (9, 'Saint Elizabeth');
insert into City(idCountry, nameCity) values (9, 'Saint James');
insert into City(idCountry, nameCity) values (9, 'Saint Mary');
insert into City(idCountry, nameCity) values (9, 'Saint Thomas');
insert into City(idCountry, nameCity) values (9, 'Trelawny');
insert into City(idCountry, nameCity) values (9, 'Westmoreland');
---Nicaragua
insert into City(idCountry, nameCity) values (10, 'Atlántico Norte');
insert into City(idCountry, nameCity) values (10, 'Atlántico Sur');
insert into City(idCountry, nameCity) values (10, 'Boaco');
insert into City(idCountry, nameCity) values (10, 'Carazo');
insert into City(idCountry, nameCity) values (10, 'Chinandega');
insert into City(idCountry, nameCity) values (10, 'Chontales');
insert into City(idCountry, nameCity) values (10, 'Estelí');
insert into City(idCountry, nameCity) values (10, 'Granada');
insert into City(idCountry, nameCity) values (10, 'Jinotega');
insert into City(idCountry, nameCity) values (10, 'León');
insert into City(idCountry, nameCity) values (10, 'Madriz');
insert into City(idCountry, nameCity) values (10, 'Managua');
insert into City(idCountry, nameCity) values (10, 'Masaya');
insert into City(idCountry, nameCity) values (10, 'Matagalpa');
insert into City(idCountry, nameCity) values (10, 'Nueva Segovia');
insert into City(idCountry, nameCity) values (10, 'Río San Juan');
insert into City(idCountry, nameCity) values (10, 'Rivas');
---Paraguay
insert into City(idCountry, nameCity) values (11, 'Alto Paraguay');
insert into City(idCountry, nameCity) values (11, 'Alto Paraná');
insert into City(idCountry, nameCity) values (11, 'Amambay');
insert into City(idCountry, nameCity) values (11, 'Asunción');
insert into City(idCountry, nameCity) values (11, 'Boquerón');
insert into City(idCountry, nameCity) values (11, 'Caaguazú');
insert into City(idCountry, nameCity) values (11, 'Caazapá');
insert into City(idCountry, nameCity) values (11, 'Canindeyú');
insert into City(idCountry, nameCity) values (11, 'Central');
insert into City(idCountry, nameCity) values (11, 'Concepción');
insert into City(idCountry, nameCity) values (11, 'Cordillera');
insert into City(idCountry, nameCity) values (11, 'Guairá');
insert into City(idCountry, nameCity) values (11, 'Itapúa');
insert into City(idCountry, nameCity) values (11, 'Misiones');
insert into City(idCountry, nameCity) values (11, 'Ñeembucú');
insert into City(idCountry, nameCity) values (11, 'Paraguarí');
insert into City(idCountry, nameCity) values (11, 'Presidente Hayes');
insert into City(idCountry, nameCity) values (11, 'San Pedro');
---Surinam
insert into City(idCountry, nameCity) values (12, 'Brokopondo');
insert into City(idCountry, nameCity) values (12, 'Commewijne');
insert into City(idCountry, nameCity) values (12, 'Coronie');
insert into City(idCountry, nameCity) values (12, 'Marowijne');
insert into City(idCountry, nameCity) values (12, 'Nickerie');
insert into City(idCountry, nameCity) values (12, 'Para');
insert into City(idCountry, nameCity) values (12, 'Paramaribo');
insert into City(idCountry, nameCity) values (12, 'Saramacca');
insert into City(idCountry, nameCity) values (12, 'Sipaliwini');
insert into City(idCountry, nameCity) values (12, 'Wanica');
---Uruguay
insert into City(idCountry, nameCity) values (13, 'Artigas');
insert into City(idCountry, nameCity) values (13, 'Canelones');
insert into City(idCountry, nameCity) values (13, 'Cerro Largo');
insert into City(idCountry, nameCity) values (13, 'Colonia');
insert into City(idCountry, nameCity) values (13, 'Durazno');
insert into City(idCountry, nameCity) values (13, 'Flores');
insert into City(idCountry, nameCity) values (13, 'Florida');
insert into City(idCountry, nameCity) values (13, 'Lavalleja');
insert into City(idCountry, nameCity) values (13, 'Maldonado');
insert into City(idCountry, nameCity) values (13, 'Montevideo');
insert into City(idCountry, nameCity) values (13, 'Paysandú');
insert into City(idCountry, nameCity) values (13, 'Río Negro');
insert into City(idCountry, nameCity) values (13, 'Rivera');
insert into City(idCountry, nameCity) values (13, 'Rocha');
insert into City(idCountry, nameCity) values (13, 'Salto');
insert into City(idCountry, nameCity) values (13, 'San José');
insert into City(idCountry, nameCity) values (13, 'Soriano');
insert into City(idCountry, nameCity) values (13, 'Tacuarembó');
insert into City(idCountry, nameCity) values (13, 'Treinta y Tres');
---Belice
insert into City(idCountry, nameCity) values (14, 'Belice');
insert into City(idCountry, nameCity) values (14, 'Cayo');
insert into City(idCountry, nameCity) values (14, 'Corozal');
insert into City(idCountry, nameCity) values (14, 'Orange Walk');
insert into City(idCountry, nameCity) values (14, 'Stann Creek');
insert into City(idCountry, nameCity) values (14, 'Toledo');
---Brasil
insert into City(idCountry, nameCity) values (15, 'Acre');
insert into City(idCountry, nameCity) values (15, 'Alagoas');
insert into City(idCountry, nameCity) values (15, 'Amapá');
insert into City(idCountry, nameCity) values (15, 'Amazonas');
insert into City(idCountry, nameCity) values (15, 'Bahia');
insert into City(idCountry, nameCity) values (15, 'Ceará');
insert into City(idCountry, nameCity) values (15, 'Distrito Federal');
insert into City(idCountry, nameCity) values (15, 'Espírito Santo');
insert into City(idCountry, nameCity) values (15, 'Goiás');
insert into City(idCountry, nameCity) values (15, 'Maranhão');
insert into City(idCountry, nameCity) values (15, 'Mato Grosso');
insert into City(idCountry, nameCity) values (15, 'Mato Grosso do Sul');
insert into City(idCountry, nameCity) values (15, 'Minas Gerais');
insert into City(idCountry, nameCity) values (15, 'Pará');
insert into City(idCountry, nameCity) values (15, 'Paraíba');
insert into City(idCountry, nameCity) values (15, 'Paraná');
insert into City(idCountry, nameCity) values (15, 'Pernambuco');
insert into City(idCountry, nameCity) values (15, 'Piauí');
insert into City(idCountry, nameCity) values (15, 'Rio de Janeiro');
insert into City(idCountry, nameCity) values (15, 'Rio Grande do Norte');
insert into City(idCountry, nameCity) values (15, 'Rio Grande do Sul');
insert into City(idCountry, nameCity) values (15, 'Rondônia');
insert into City(idCountry, nameCity) values (15, 'Roraima');
insert into City(idCountry, nameCity) values (15, 'Santa Catarina');
insert into City(idCountry, nameCity) values (15, 'São Paulo');
insert into City(idCountry, nameCity) values (15, 'Sergipe');
insert into City(idCountry, nameCity) values (15, 'Tocantins');
---Chile
insert into City(idCountry, nameCity) values (16, 'Aysén del General Carlos Ibáñez del Campo');
insert into City(idCountry, nameCity) values (16, 'Antofagasta');
insert into City(idCountry, nameCity) values (16, 'La Araucanía');
insert into City(idCountry, nameCity) values (16, 'Arica y Parinacota');
insert into City(idCountry, nameCity) values (16, 'Atacama');
insert into City(idCountry, nameCity) values (16, 'Bio Bio');
insert into City(idCountry, nameCity) values (16, 'Coquimbo');
insert into City(idCountry, nameCity) values (16, 'Los Ríos');
insert into City(idCountry, nameCity) values (16, 'General Libertador Bernardo O´Higgins');
insert into City(idCountry, nameCity) values (16, 'Los Lagos');
insert into City(idCountry, nameCity) values (16, 'Magallanes y de la Antártica Chilena');
insert into City(idCountry, nameCity) values (16, 'Maule');
insert into City(idCountry, nameCity) values (16, 'Ñuble');
insert into City(idCountry, nameCity) values (16, 'Santiago');
insert into City(idCountry, nameCity) values (16, 'Tarapacá');
insert into City(idCountry, nameCity) values (16, 'Valparaíso');
---Republica dominicana
insert into City(idCountry, nameCity) values (17, 'Azua');
insert into City(idCountry, nameCity) values (17, 'Baoruco');
insert into City(idCountry, nameCity) values (17, 'Barahona');
insert into City(idCountry, nameCity) values (17, 'Dajabón');
insert into City(idCountry, nameCity) values (17, 'Duarte');
insert into City(idCountry, nameCity) values (17, 'El Seibo');
insert into City(idCountry, nameCity) values (17, 'Elías Piña');
insert into City(idCountry, nameCity) values (17, 'Espaillat');
insert into City(idCountry, nameCity) values (17, 'Hato Mayor');
insert into City(idCountry, nameCity) values (17, 'Hermanas Mirabal');
insert into City(idCountry, nameCity) values (17, 'Independencia');
insert into City(idCountry, nameCity) values (17, 'La Altagracia');
insert into City(idCountry, nameCity) values (17, 'La Romana');
insert into City(idCountry, nameCity) values (17, 'La Vega');
insert into City(idCountry, nameCity) values (17, 'María Trinidad Sánchez');
insert into City(idCountry, nameCity) values (17, 'Monseñor Nouel');
insert into City(idCountry, nameCity) values (17, 'Monte Cristi');
insert into City(idCountry, nameCity) values (17, 'Monte Plata');
insert into City(idCountry, nameCity) values (17, 'Pedernales');
insert into City(idCountry, nameCity) values (17, 'Peravia');
insert into City(idCountry, nameCity) values (17, 'Puerto Plata');
insert into City(idCountry, nameCity) values (17, 'Samaná');
insert into City(idCountry, nameCity) values (17, 'San Cristóbal');
insert into City(idCountry, nameCity) values (17, 'San José de Ocoa');
insert into City(idCountry, nameCity) values (17, 'San Juan');
insert into City(idCountry, nameCity) values (17, 'San Pedro de Macorís');
insert into City(idCountry, nameCity) values (17, 'Sánchez Ramírez');
insert into City(idCountry, nameCity) values (17, 'Santiago');
insert into City(idCountry, nameCity) values (17, 'Santiago Rodríguez');
insert into City(idCountry, nameCity) values (17, 'Santo Domingo');
insert into City(idCountry, nameCity) values (17, 'Valverde');
---El salvador
insert into City(idCountry, nameCity) values (18, 'Ahuachapán');
insert into City(idCountry, nameCity) values (18, 'Cabañas');
insert into City(idCountry, nameCity) values (18, 'Chalatenango');
insert into City(idCountry, nameCity) values (18, 'Cuscatlán');
insert into City(idCountry, nameCity) values (18, 'La Libertad');
insert into City(idCountry, nameCity) values (18, 'La Paz');
insert into City(idCountry, nameCity) values (18, 'La Unión');
insert into City(idCountry, nameCity) values (18, 'Morazán');
insert into City(idCountry, nameCity) values (18, 'San Miguel');
insert into City(idCountry, nameCity) values (18, 'San Salvador');
insert into City(idCountry, nameCity) values (18, 'San Vicente');
insert into City(idCountry, nameCity) values (18, 'Santa Ana');
insert into City(idCountry, nameCity) values (18, 'Sonsonate');
insert into City(idCountry, nameCity) values (18, 'Usulután');
---Guyana
insert into City(idCountry, nameCity) values (19, 'Barima-Waini');
insert into City(idCountry, nameCity) values (19, 'Berbice Oriental-Corentyne');
insert into City(idCountry, nameCity) values (19, 'Cuyuni-Mazaruni');
insert into City(idCountry, nameCity) values (19, 'Demerara-Mahaica');
insert into City(idCountry, nameCity) values (19, 'Alto Demerara-Berbice');
insert into City(idCountry, nameCity) values (19, 'Alto Takutu-Alto Esequibo');
insert into City(idCountry, nameCity) values (19, 'Islas del Esequibo-Demerara Occidental');
insert into City(idCountry, nameCity) values (19, 'Mahaica-Berbice');
insert into City(idCountry, nameCity) values (19, 'Pomeroon-Supenaam');
insert into City(idCountry, nameCity) values (19, 'Potaro-Siparuni');
---Honduras
insert into City(idCountry, nameCity) values (20, 'Atlántida');
insert into City(idCountry, nameCity) values (20, 'Choluteca');
insert into City(idCountry, nameCity) values (20, 'Colón');
insert into City(idCountry, nameCity) values (20, 'Comayagua');
insert into City(idCountry, nameCity) values (20, 'Copán');
insert into City(idCountry, nameCity) values (20, 'Cortés');
insert into City(idCountry, nameCity) values (20, 'El Paraíso');
insert into City(idCountry, nameCity) values (20, 'Francisco Morazán');
insert into City(idCountry, nameCity) values (20, 'Gracias a Dios');
insert into City(idCountry, nameCity) values (20, 'Intibucá');
insert into City(idCountry, nameCity) values (20, 'Islas de la Bahía');
insert into City(idCountry, nameCity) values (20, 'La Paz');
insert into City(idCountry, nameCity) values (20, 'Lempira');
insert into City(idCountry, nameCity) values (20, 'Ocotepeque');
insert into City(idCountry, nameCity) values (20, 'Olancho');
insert into City(idCountry, nameCity) values (20, 'Santa Bárbara');
insert into City(idCountry, nameCity) values (20, 'Valle');
insert into City(idCountry, nameCity) values (20, 'Yoro');
---México
insert into City(idCountry, nameCity) values (21, 'Aguascalientes');
insert into City(idCountry, nameCity) values (21, 'Baja California');
insert into City(idCountry, nameCity) values (21, 'Baja California Sur');
insert into City(idCountry, nameCity) values (21, 'Campeche');
insert into City(idCountry, nameCity) values (21, 'Chiapas');
insert into City(idCountry, nameCity) values (21, 'Chihuahua');
insert into City(idCountry, nameCity) values (21, 'Distrito Federal');
insert into City(idCountry, nameCity) values (21, 'Coahuila');
insert into City(idCountry, nameCity) values (21, 'Colima');
insert into City(idCountry, nameCity) values (21, 'Durango');
insert into City(idCountry, nameCity) values (21, 'Guanajuato');
insert into City(idCountry, nameCity) values (21, 'Guerrero');
insert into City(idCountry, nameCity) values (21, 'Hidalgo');
insert into City(idCountry, nameCity) values (21, 'Jalisco');
insert into City(idCountry, nameCity) values (21, 'México');
insert into City(idCountry, nameCity) values (21, 'Michoacán');
insert into City(idCountry, nameCity) values (21, 'Morelos');
insert into City(idCountry, nameCity) values (21, 'Nayarit');
insert into City(idCountry, nameCity) values (21, 'Nuevo León');
insert into City(idCountry, nameCity) values (21, 'Oaxaca');
insert into City(idCountry, nameCity) values (21, 'Puebla');
insert into City(idCountry, nameCity) values (21, 'Querétaro');
insert into City(idCountry, nameCity) values (21, 'Quintana Roo');
insert into City(idCountry, nameCity) values (21, 'San Luis Potosí');
insert into City(idCountry, nameCity) values (21, 'Sinaloa');
insert into City(idCountry, nameCity) values (21, 'Sonora');
insert into City(idCountry, nameCity) values (21, 'Tabasco');
insert into City(idCountry, nameCity) values (21, 'Tamaulipas');
insert into City(idCountry, nameCity) values (21, 'Tlaxcala');
insert into City(idCountry, nameCity) values (21, 'Veracruz de Ignacio de la Llave');
insert into City(idCountry, nameCity) values (21, 'Yucatán');
insert into City(idCountry, nameCity) values (21, 'Zacatecas');
---Panamá
insert into City(idCountry, nameCity) values (22, 'Bocas del Toro');
insert into City(idCountry, nameCity) values (22, 'Chiriquí');
insert into City(idCountry, nameCity) values (22, 'Coclé');
insert into City(idCountry, nameCity) values (22, 'Colón');
insert into City(idCountry, nameCity) values (22, 'Darién');
insert into City(idCountry, nameCity) values (22, 'Emberá-Wounaan');
insert into City(idCountry, nameCity) values (22, 'Guna Yala');
insert into City(idCountry, nameCity) values (22, 'Herrera');
insert into City(idCountry, nameCity) values (22, 'Los Santos');
insert into City(idCountry, nameCity) values (22, 'Ngäbe-Buglé');
insert into City(idCountry, nameCity) values (22, 'Panamá');
insert into City(idCountry, nameCity) values (22, 'Panamá Oeste');
insert into City(idCountry, nameCity) values (22, 'Veraguas');
---Perú
insert into City(idCountry, nameCity) values (23, 'Amazonas');
insert into City(idCountry, nameCity) values (23, 'Áncash');
insert into City(idCountry, nameCity) values (23, 'Apurímac');
insert into City(idCountry, nameCity) values (23, 'Arequipa');
insert into City(idCountry, nameCity) values (23, 'Ayacucho');
insert into City(idCountry, nameCity) values (23, 'Cajamarca');
insert into City(idCountry, nameCity) values (23, 'Callao');
insert into City(idCountry, nameCity) values (23, 'Cusco');
insert into City(idCountry, nameCity) values (23, 'Huancavelica');
insert into City(idCountry, nameCity) values (23, 'Huánuco');
insert into City(idCountry, nameCity) values (23, 'Ica');
insert into City(idCountry, nameCity) values (23, 'Junín');
insert into City(idCountry, nameCity) values (23, 'La Libertad');
insert into City(idCountry, nameCity) values (23, 'Lambayeque');
insert into City(idCountry, nameCity) values (23, 'Lima');
insert into City(idCountry, nameCity) values (23, 'Loreto');
insert into City(idCountry, nameCity) values (23, 'Madre de Dios');
insert into City(idCountry, nameCity) values (23, 'Moquegua');
insert into City(idCountry, nameCity) values (23, 'Pasco');
insert into City(idCountry, nameCity) values (23, 'Piura');
insert into City(idCountry, nameCity) values (23, 'Puno');
insert into City(idCountry, nameCity) values (23, 'San Martín');
insert into City(idCountry, nameCity) values (23, 'Tacna');
insert into City(idCountry, nameCity) values (23, 'Tumbes');
insert into City(idCountry, nameCity) values (23, 'Ucayali');
---Estados Unidos
insert into City(idCountry, nameCity) values (24, 'Alabama');
insert into City(idCountry, nameCity) values (24, 'Alaska');
insert into City(idCountry, nameCity) values (24, 'Arizona');
insert into City(idCountry, nameCity) values (24, 'Arkansas');
insert into City(idCountry, nameCity) values (24, 'California');
insert into City(idCountry, nameCity) values (24, 'California del Norte');
insert into City(idCountry, nameCity) values (24, 'California del Sur');
insert into City(idCountry, nameCity) values (24, 'Colorado');
insert into City(idCountry, nameCity) values (24, 'Columbia');
insert into City(idCountry, nameCity) values (24, 'Connecticut');
insert into City(idCountry, nameCity) values (24, 'Dakota del Norte');
insert into City(idCountry, nameCity) values (24, 'Dakota del Sur');
insert into City(idCountry, nameCity) values (24, 'Delaware');
insert into City(idCountry, nameCity) values (24, 'Florida');
insert into City(idCountry, nameCity) values (24, 'Georgia');
insert into City(idCountry, nameCity) values (24, 'Hawái');
insert into City(idCountry, nameCity) values (24, 'Idaho');
insert into City(idCountry, nameCity) values (24, 'Illinois');
insert into City(idCountry, nameCity) values (24, 'Indiana');
insert into City(idCountry, nameCity) values (24, 'Iowa');
insert into City(idCountry, nameCity) values (24, 'Kansas');
insert into City(idCountry, nameCity) values (24, 'Kentucky');
insert into City(idCountry, nameCity) values (24, 'Louisiana');
insert into City(idCountry, nameCity) values (24, 'Maine');
insert into City(idCountry, nameCity) values (24, 'Maryland');
insert into City(idCountry, nameCity) values (24, 'Massachusetts');
insert into City(idCountry, nameCity) values (24, 'Michigan');
insert into City(idCountry, nameCity) values (24, 'Minnesota');
insert into City(idCountry, nameCity) values (24, 'Mississippi');
insert into City(idCountry, nameCity) values (24, 'Missouri');
insert into City(idCountry, nameCity) values (24, 'Montana');
insert into City(idCountry, nameCity) values (24, 'Nebraska');
insert into City(idCountry, nameCity) values (24, 'Nevada');
insert into City(idCountry, nameCity) values (24, 'Nuevo Hampshire');
insert into City(idCountry, nameCity) values (24, 'Nueva Jersey');
insert into City(idCountry, nameCity) values (24, 'Nuevo Mexico');
insert into City(idCountry, nameCity) values (24, 'Nueva York');
insert into City(idCountry, nameCity) values (24, 'Ohio');
insert into City(idCountry, nameCity) values (24, 'Oklahoma');
insert into City(idCountry, nameCity) values (24, 'Oregon');
insert into City(idCountry, nameCity) values (24, 'Pensilvania');
insert into City(idCountry, nameCity) values (24, 'Rhode Island');
insert into City(idCountry, nameCity) values (24, 'Tennessee');
insert into City(idCountry, nameCity) values (24, 'Texas');
insert into City(idCountry, nameCity) values (24, 'Utah');
insert into City(idCountry, nameCity) values (24, 'Vermont');
insert into City(idCountry, nameCity) values (24, 'Virginia');
insert into City(idCountry, nameCity) values (24, 'Virginia Occidental');
insert into City(idCountry, nameCity) values (24, 'Washington');
insert into City(idCountry, nameCity) values (24, 'Wisconsin');
insert into City(idCountry, nameCity) values (24, 'Wyoming');
---Venezuela
insert into City(idCountry, nameCity) values (25, 'Amazonas');
insert into City(idCountry, nameCity) values (25, 'Anzoátegui');
insert into City(idCountry, nameCity) values (25, 'Apure');
insert into City(idCountry, nameCity) values (25, 'Aragua');
insert into City(idCountry, nameCity) values (25, 'Barinas');
insert into City(idCountry, nameCity) values (25, 'Bolívar');
insert into City(idCountry, nameCity) values (25, 'Carabobo');
insert into City(idCountry, nameCity) values (25, 'Cojedes');
insert into City(idCountry, nameCity) values (25, 'Delta Amacuro');
insert into City(idCountry, nameCity) values (25, 'Dependencias Federales');
insert into City(idCountry, nameCity) values (25, 'Distrito Metropolitano de Caracas');
insert into City(idCountry, nameCity) values (25, 'Falcón');
insert into City(idCountry, nameCity) values (25, 'Guárico');
insert into City(idCountry, nameCity) values (25, 'Lara');
insert into City(idCountry, nameCity) values (25, 'Mérida');
insert into City(idCountry, nameCity) values (25, 'Miranda');
insert into City(idCountry, nameCity) values (25, 'Monagas');
insert into City(idCountry, nameCity) values (25, 'Nueva Esparta');
insert into City(idCountry, nameCity) values (25, 'Portuguesa');
insert into City(idCountry, nameCity) values (25, 'Sucre');
insert into City(idCountry, nameCity) values (25, 'Táchira');
insert into City(idCountry, nameCity) values (25, 'Trujillo');
insert into City(idCountry, nameCity) values (25, 'Vargas');
insert into City(idCountry, nameCity) values (25, 'Yaracuy');
insert into City(idCountry, nameCity) values (25, 'Zulia');



/***********EUROPA********************/
---Albania
insert into City(idCountry, nameCity) values (26, 'Berat');
insert into City(idCountry, nameCity) values (26, 'Dibër');
insert into City(idCountry, nameCity) values (26, 'Durrës');
insert into City(idCountry, nameCity) values (26, 'Elbasan');
insert into City(idCountry, nameCity) values (26, 'Fier');
insert into City(idCountry, nameCity) values (26, 'Gjirokastër');
insert into City(idCountry, nameCity) values (26, 'Korçë');
insert into City(idCountry, nameCity) values (26, 'Kukës');
insert into City(idCountry, nameCity) values (26, 'Lezhë');
insert into City(idCountry, nameCity) values (26, 'Shkodër');
insert into City(idCountry, nameCity) values (26, 'Tiranë');
insert into City(idCountry, nameCity) values (26, 'Vlorë');
---Austria
insert into City(idCountry, nameCity) values (27, 'Burgenland');
insert into City(idCountry, nameCity) values (27, 'Carintia');
insert into City(idCountry, nameCity) values (27, 'Baja Austria');
insert into City(idCountry, nameCity) values (27, 'Alta Austria');
insert into City(idCountry, nameCity) values (27, 'Salzburgo');
insert into City(idCountry, nameCity) values (27, 'Estiria');
insert into City(idCountry, nameCity) values (27, 'Tirol');
insert into City(idCountry, nameCity) values (27, 'Vorarlberg');
insert into City(idCountry, nameCity) values (27, 'Viena');
---Bosnia y Herzegovina
insert into City(idCountry, nameCity) values (28, 'Distrito de Brcko');
insert into City(idCountry, nameCity) values (28, 'Federación de Bosnia y Herzegovina');
insert into City(idCountry, nameCity) values (28, 'República Srpska');
---Croacia
insert into City(idCountry, nameCity) values (29, 'Bjelovar-Bilogora');
insert into City(idCountry, nameCity) values (29, 'Brod-Posavina');
insert into City(idCountry, nameCity) values (29, 'Dubrovnik-Neretva');
insert into City(idCountry, nameCity) values (29, 'Istria');
insert into City(idCountry, nameCity) values (29, 'Karlovac');
insert into City(idCountry, nameCity) values (29, 'Koprivnica-Križevci');
insert into City(idCountry, nameCity) values (29, 'Krapina-Zagorje');
insert into City(idCountry, nameCity) values (29, 'Lika-Senj');
insert into City(idCountry, nameCity) values (29, 'Međimurje');
insert into City(idCountry, nameCity) values (29, 'Osijek-Baranja');
insert into City(idCountry, nameCity) values (29, 'Požega-Eslavonia');
insert into City(idCountry, nameCity) values (29, 'Primorje-Gorski Kotar');
insert into City(idCountry, nameCity) values (29, 'Šibenik-Knin');
insert into City(idCountry, nameCity) values (29, 'Sisak-Moslavina');
insert into City(idCountry, nameCity) values (29, 'Split-Dalmacia');
insert into City(idCountry, nameCity) values (29, 'Varaždin');
insert into City(idCountry, nameCity) values (29, 'Virovitica-Podravina');
insert into City(idCountry, nameCity) values (29, 'Vukovar-Sirmia');
insert into City(idCountry, nameCity) values (29, 'Zadar');
insert into City(idCountry, nameCity) values (29, 'Zagreb');
---Dinamarca
insert into City(idCountry, nameCity) values (30, 'Syddanmark');
insert into City(idCountry, nameCity) values (30, 'Hovedstaden');
insert into City(idCountry, nameCity) values (30, 'Midtjylland');
insert into City(idCountry, nameCity) values (30, 'Nordjylland');
insert into City(idCountry, nameCity) values (30, 'Region Sjælland');
---Francia
insert into City(idCountry, nameCity) values (31, 'Auvernia-Ródano-Alpes');
insert into City(idCountry, nameCity) values (31, 'Borgoña-Franco Condado');
insert into City(idCountry, nameCity) values (31, 'Bretaña');
insert into City(idCountry, nameCity) values (31, 'Centro-Valle de Loira');
insert into City(idCountry, nameCity) values (31, 'Colectividad de ultramar');
insert into City(idCountry, nameCity) values (31, 'Corcega');
insert into City(idCountry, nameCity) values (31, 'Gran Este');
insert into City(idCountry, nameCity) values (31, 'Hauts-de-France');
insert into City(idCountry, nameCity) values (31, 'Isla de Francia');
insert into City(idCountry, nameCity) values (31, 'Normandía');
insert into City(idCountry, nameCity) values (31, 'Nueva Aquitania');
insert into City(idCountry, nameCity) values (31, 'Occitania');
insert into City(idCountry, nameCity) values (31, 'Países del Loira');
insert into City(idCountry, nameCity) values (31, 'Provenza-Alpes-Costa Azul');
---Grecia
insert into City(idCountry, nameCity) values (32, 'Ática');
insert into City(idCountry, nameCity) values (32, 'Creta');
insert into City(idCountry, nameCity) values (32, 'Egeo Meridional');
insert into City(idCountry, nameCity) values (32, 'Egeo Septentrional');
insert into City(idCountry, nameCity) values (32, 'Epiro');
insert into City(idCountry, nameCity) values (32, 'Grecia Central');
insert into City(idCountry, nameCity) values (32, 'Grecia Occidental');
insert into City(idCountry, nameCity) values (32, 'Islas Jónicas');
insert into City(idCountry, nameCity) values (32, 'Macedonia Central');
insert into City(idCountry, nameCity) values (32, 'Macedonia Occidental');
insert into City(idCountry, nameCity) values (32, 'Macedonia Oriental y Tracia');
insert into City(idCountry, nameCity) values (32, 'Monte Athos');
insert into City(idCountry, nameCity) values (32, 'Peloponeso');
insert into City(idCountry, nameCity) values (32, 'Tesalia');
---Hungría
insert into City(idCountry, nameCity) values (33, 'Bács-Kiskun');
insert into City(idCountry, nameCity) values (33, 'Baranya');
insert into City(idCountry, nameCity) values (33, 'Békés');
insert into City(idCountry, nameCity) values (33, 'Borsod-Abaúj-Zemplén');
insert into City(idCountry, nameCity) values (33, 'Budapest');
insert into City(idCountry, nameCity) values (33, 'Csongrád');
insert into City(idCountry, nameCity) values (33, 'Fejér');
insert into City(idCountry, nameCity) values (33, 'Győr-Moson-Sopron');
insert into City(idCountry, nameCity) values (33, 'Hajdú-Bihar');
insert into City(idCountry, nameCity) values (33, 'Heves');
insert into City(idCountry, nameCity) values (33, 'Jász-Nagykun-Szolnok');
insert into City(idCountry, nameCity) values (33, 'Komárom-Esztergom');
insert into City(idCountry, nameCity) values (33, 'Nógrád');
insert into City(idCountry, nameCity) values (33, 'Pest');
insert into City(idCountry, nameCity) values (33, 'Somogy');
insert into City(idCountry, nameCity) values (33, 'Szabolcs-Szatmár-Bereg');
insert into City(idCountry, nameCity) values (33, 'Tolna');
insert into City(idCountry, nameCity) values (33, 'Vas');
insert into City(idCountry, nameCity) values (33, 'Veszprém');
insert into City(idCountry, nameCity) values (33, 'Zala');
---Irlanda
insert into City(idCountry, nameCity) values (34, 'Carlow');
insert into City(idCountry, nameCity) values (34, 'Cavan');
insert into City(idCountry, nameCity) values (34, 'Clare');
insert into City(idCountry, nameCity) values (34, 'Cork');
insert into City(idCountry, nameCity) values (34, 'Donegal');
insert into City(idCountry, nameCity) values (34, 'Dublín');
insert into City(idCountry, nameCity) values (34, 'Dublín Sur');
insert into City(idCountry, nameCity) values (34, 'Dún Laoghaire-Rathdown');
insert into City(idCountry, nameCity) values (34, 'Fingal');
insert into City(idCountry, nameCity) values (34, 'Galway');
insert into City(idCountry, nameCity) values (34, 'Kerry');
insert into City(idCountry, nameCity) values (34, 'Kildare');
insert into City(idCountry, nameCity) values (34, 'Kilkenny');
insert into City(idCountry, nameCity) values (34, 'Laois');
insert into City(idCountry, nameCity) values (34, 'Leitrim');
insert into City(idCountry, nameCity) values (34, 'Limerick');
insert into City(idCountry, nameCity) values (34, 'Longford');
insert into City(idCountry, nameCity) values (34, 'Louth');
insert into City(idCountry, nameCity) values (34, 'Mayo');
insert into City(idCountry, nameCity) values (34, 'Meath');
insert into City(idCountry, nameCity) values (34, 'Monaghan');
insert into City(idCountry, nameCity) values (34, 'Offaly');
insert into City(idCountry, nameCity) values (34, 'Roscommon');
insert into City(idCountry, nameCity) values (34, 'Sligo');
insert into City(idCountry, nameCity) values (34, 'Tipperary');
insert into City(idCountry, nameCity) values (34, 'Waterford');
insert into City(idCountry, nameCity) values (34, 'Westmeath');
insert into City(idCountry, nameCity) values (34, 'Wexford');
insert into City(idCountry, nameCity) values (34, 'Wicklow');
---Letonia
insert into City(idCountry, nameCity) values (35, 'Vidzeme');
insert into City(idCountry, nameCity) values (35, 'Latgale');
insert into City(idCountry, nameCity) values (35, 'Kurzeme');
insert into City(idCountry, nameCity) values (35, 'Zemgale');
insert into City(idCountry, nameCity) values (35, 'Riga');
---Lituania
insert into City(idCountry, nameCity) values (36, 'Alytus');
insert into City(idCountry, nameCity) values (36, 'Kaunas');
insert into City(idCountry, nameCity) values (36, 'Klaipeda');
insert into City(idCountry, nameCity) values (36, 'Marijampole');
insert into City(idCountry, nameCity) values (36, 'Panevezys');
insert into City(idCountry, nameCity) values (36, 'Siauliai');
insert into City(idCountry, nameCity) values (36, 'Taurage');
insert into City(idCountry, nameCity) values (36, 'Telsiai');
insert into City(idCountry, nameCity) values (36, 'Utena');
insert into City(idCountry, nameCity) values (36, 'Vilna');
---Macedonia del Norte
insert into City(idCountry, nameCity) values (37, 'Este');
insert into City(idCountry, nameCity) values (37, 'Noreste');
insert into City(idCountry, nameCity) values (37, 'Pelagonia');
insert into City(idCountry, nameCity) values (37, 'Polog');
insert into City(idCountry, nameCity) values (37, 'Skopje');
insert into City(idCountry, nameCity) values (37, 'Sudeste');
insert into City(idCountry, nameCity) values (37, 'Sudoeste');
insert into City(idCountry, nameCity) values (37, 'Vardar');
---Mónaco
insert into City(idCountry, nameCity) values (38, 'Mónaco');
---Noruega
insert into City(idCountry, nameCity) values (39, 'Agder');
insert into City(idCountry, nameCity) values (39, 'Innalandet');
insert into City(idCountry, nameCity) values (39, 'Møre og Romsdal');
insert into City(idCountry, nameCity) values (39, 'Nordland');
insert into City(idCountry, nameCity) values (39, 'Oslo');
insert into City(idCountry, nameCity) values (39, 'Rogaland');
insert into City(idCountry, nameCity) values (39, 'Troms og Finnmark');
insert into City(idCountry, nameCity) values (39, 'Trøndelag');
insert into City(idCountry, nameCity) values (39, 'Vestfold og Telemark');
insert into City(idCountry, nameCity) values (39, 'Vestland');
insert into City(idCountry, nameCity) values (39, 'Viken');
---Portugal
insert into City(idCountry, nameCity) values (40, 'Açores');
insert into City(idCountry, nameCity) values (40, 'Aveiro');
insert into City(idCountry, nameCity) values (40, 'Beja');
insert into City(idCountry, nameCity) values (40, 'Braga');
insert into City(idCountry, nameCity) values (40, 'Braganza');
insert into City(idCountry, nameCity) values (40, 'Castelo Branco');
insert into City(idCountry, nameCity) values (40, 'Coimbra');
insert into City(idCountry, nameCity) values (40, 'Évora');
insert into City(idCountry, nameCity) values (40, 'Faro');
insert into City(idCountry, nameCity) values (40, 'Guarda');
insert into City(idCountry, nameCity) values (40, 'Leiria');
insert into City(idCountry, nameCity) values (40, 'Lisboa');
insert into City(idCountry, nameCity) values (40, 'Madeira');
insert into City(idCountry, nameCity) values (40, 'Portalegre');
insert into City(idCountry, nameCity) values (40, 'Porto');
insert into City(idCountry, nameCity) values (40, 'Santarém');
insert into City(idCountry, nameCity) values (40, 'Setúbal');
insert into City(idCountry, nameCity) values (40, 'Viana do Castelo');
insert into City(idCountry, nameCity) values (40, 'Vila Real');
insert into City(idCountry, nameCity) values (40, 'Viseu');
---Rusia
insert into City(idCountry, nameCity) values (41, 'Adigueya');
insert into City(idCountry, nameCity) values (41, 'Krai de Altái');
insert into City(idCountry, nameCity) values (41, 'República de Atái');
insert into City(idCountry, nameCity) values (41, 'Amur');
insert into City(idCountry, nameCity) values (41, 'Arjángelsk');
insert into City(idCountry, nameCity) values (41, 'Astracán');
insert into City(idCountry, nameCity) values (41, 'Bashkortostán');
insert into City(idCountry, nameCity) values (41, 'Bélgorod');
insert into City(idCountry, nameCity) values (41, 'Buriatia');
insert into City(idCountry, nameCity) values (41, 'Briansk');
insert into City(idCountry, nameCity) values (41, 'Carelia');
insert into City(idCountry, nameCity) values (41, 'Daguestán');
insert into City(idCountry, nameCity) values (41, 'Yamalia-Nenetsia');
insert into City(idCountry, nameCity) values (41, 'Yoroslavl');
insert into City(idCountry, nameCity) values (41, 'Ingusetia');
insert into City(idCountry, nameCity) values (41, 'Irkutsk');
insert into City(idCountry, nameCity) values (41, 'Ivánovo');
insert into City(idCountry, nameCity) values (41, 'Kabardia-Balkaria');
insert into City(idCountry, nameCity) values (41, 'Kaliningrado');
insert into City(idCountry, nameCity) values (41, 'Kalmukia');
insert into City(idCountry, nameCity) values (41, 'Kaluga');
insert into City(idCountry, nameCity) values (41, 'Kamchatka');
insert into City(idCountry, nameCity) values (41, 'Karachay-Circasia');
insert into City(idCountry, nameCity) values (41, 'Kémerovo');
insert into City(idCountry, nameCity) values (41, 'Jabárovsk');
insert into City(idCountry, nameCity) values (41, 'Khakasiya');
insert into City(idCountry, nameCity) values (41, 'Janti-Mansi');
insert into City(idCountry, nameCity) values (41, 'Kírov');
insert into City(idCountry, nameCity) values (41, 'Komi');
insert into City(idCountry, nameCity) values (41, 'Kostromá');
insert into City(idCountry, nameCity) values (41, 'Kurgán');
insert into City(idCountry, nameCity) values (41, 'Kursk');
insert into City(idCountry, nameCity) values (41, 'Leningrado');
insert into City(idCountry, nameCity) values (41, 'Lipetsk');
insert into City(idCountry, nameCity) values (41, 'Magadan');
insert into City(idCountry, nameCity) values (41, 'Mari-El');
insert into City(idCountry, nameCity) values (41, 'Mordovia');
insert into City(idCountry, nameCity) values (41, 'Moscú');
insert into City(idCountry, nameCity) values (41, 'Óblast de Moscú');
insert into City(idCountry, nameCity) values (41, 'Múrmansk');
insert into City(idCountry, nameCity) values (41, 'Nenetsia');
insert into City(idCountry, nameCity) values (41, 'Nizhni Nóvgorod');
insert into City(idCountry, nameCity) values (41, 'Nóvgorod');
insert into City(idCountry, nameCity) values (41, 'Novosibirsk');
insert into City(idCountry, nameCity) values (41, 'Óblast Autonómo Hebreo');
insert into City(idCountry, nameCity) values (41, 'Omsk');
insert into City(idCountry, nameCity) values (41, 'Oriol');
insert into City(idCountry, nameCity) values (41, 'Oremburgo');
insert into City(idCountry, nameCity) values (41, 'Osetia del Norte - Alania');
insert into City(idCountry, nameCity) values (41, 'Udmurtia');
insert into City(idCountry, nameCity) values (41, 'Uliánovsk');
insert into City(idCountry, nameCity) values (41, 'Penza');
insert into City(idCountry, nameCity) values (41, 'Perm');
insert into City(idCountry, nameCity) values (41, 'Primorie');
insert into City(idCountry, nameCity) values (41, 'Pskov');
insert into City(idCountry, nameCity) values (41, 'Riazán');
insert into City(idCountry, nameCity) values (41, 'Rostov');
insert into City(idCountry, nameCity) values (41, 'San Petersburgo');
insert into City(idCountry, nameCity) values (41, 'Sajá');
insert into City(idCountry, nameCity) values (41, 'Sajalín');
insert into City(idCountry, nameCity) values (41, 'Samara');
insert into City(idCountry, nameCity) values (41, 'Sarátov');
insert into City(idCountry, nameCity) values (41, 'Smolensk');
insert into City(idCountry, nameCity) values (41, 'Stávropol');
insert into City(idCountry, nameCity) values (41, 'Sverdlovsk');
insert into City(idCountry, nameCity) values (41, 'Tambov');
insert into City(idCountry, nameCity) values (41, 'Tartaristán');
insert into City(idCountry, nameCity) values (41, 'Cheliábinsk');
insert into City(idCountry, nameCity) values (41, 'Chechenia');
insert into City(idCountry, nameCity) values (41, 'Chukotka');
insert into City(idCountry, nameCity) values (41, 'Chuvasia');
insert into City(idCountry, nameCity) values (41, 'Tiumén');
insert into City(idCountry, nameCity) values (41, 'Tomsk');
insert into City(idCountry, nameCity) values (41, 'Tula');
insert into City(idCountry, nameCity) values (41, 'Tuvá');
insert into City(idCountry, nameCity) values (41, 'Zabaikalie');
insert into City(idCountry, nameCity) values (41, 'Tver');
insert into City(idCountry, nameCity) values (41, 'Vladimir');
insert into City(idCountry, nameCity) values (41, 'Volgogrado');
insert into City(idCountry, nameCity) values (41, 'Vólogda');
insert into City(idCountry, nameCity) values (41, 'Vorónezh');
---Eslovaquia
insert into City(idCountry, nameCity) values (42, 'Banská Bystrica');
insert into City(idCountry, nameCity) values (42, 'Bratislava');
insert into City(idCountry, nameCity) values (42, 'Košice');
insert into City(idCountry, nameCity) values (42, 'Nitra');
insert into City(idCountry, nameCity) values (42, 'Prešov');
insert into City(idCountry, nameCity) values (42, 'Trenčín');
insert into City(idCountry, nameCity) values (42, 'Trnava');
insert into City(idCountry, nameCity) values (42, 'Žilina');
---España
insert into City(idCountry, nameCity) values (43, 'Andalucía');
insert into City(idCountry, nameCity) values (43, 'Aragón');
insert into City(idCountry, nameCity) values (43, 'Principado de Asturias');
insert into City(idCountry, nameCity) values (43, 'Cantabria');
insert into City(idCountry, nameCity) values (43, 'Castilla y León');
insert into City(idCountry, nameCity) values (43, 'Castilla-La Mancha');
insert into City(idCountry, nameCity) values (43, 'Cataluña');
insert into City(idCountry, nameCity) values (43, 'Ceuta');
insert into City(idCountry, nameCity) values (43, 'Extremadura');
insert into City(idCountry, nameCity) values (43, 'Galicia');
insert into City(idCountry, nameCity) values (43, 'Baleares');
insert into City(idCountry, nameCity) values (43, 'Canarias');
insert into City(idCountry, nameCity) values (43, 'La Rioja');
insert into City(idCountry, nameCity) values (43, 'Madrid');
insert into City(idCountry, nameCity) values (43, 'Melilla');
insert into City(idCountry, nameCity) values (43, 'Murcia');
insert into City(idCountry, nameCity) values (43, 'Navarra');
insert into City(idCountry, nameCity) values (43, 'País Vasco');
insert into City(idCountry, nameCity) values (43, 'Valenciana');
---Suiza
insert into City(idCountry, nameCity) values (44, 'Appenzell Rodas Exteriores');
insert into City(idCountry, nameCity) values (44, 'Appenzell Rodas Interiores');
insert into City(idCountry, nameCity) values (44, 'Argovia');
insert into City(idCountry, nameCity) values (44, 'Basilea-Campiña');
insert into City(idCountry, nameCity) values (44, 'Basilea-Ciudad');
insert into City(idCountry, nameCity) values (44, 'Berna');
insert into City(idCountry, nameCity) values (44, 'Friburgo');
insert into City(idCountry, nameCity) values (44, 'Ginebra');
insert into City(idCountry, nameCity) values (44, 'Glaris');
insert into City(idCountry, nameCity) values (44, 'Grisones');
insert into City(idCountry, nameCity) values (44, 'Jura');
insert into City(idCountry, nameCity) values (44, 'Lucerna');
insert into City(idCountry, nameCity) values (44, 'Neuchâtel');
insert into City(idCountry, nameCity) values (44, 'Nidwalden');
insert into City(idCountry, nameCity) values (44, 'Obwalden');
insert into City(idCountry, nameCity) values (44, 'San Galo');
insert into City(idCountry, nameCity) values (44, 'Schaffhausen');
insert into City(idCountry, nameCity) values (44, 'Schwyz');
insert into City(idCountry, nameCity) values (44, 'Soleura');
insert into City(idCountry, nameCity) values (44, 'Tesino');
insert into City(idCountry, nameCity) values (44, 'Turgovia');
insert into City(idCountry, nameCity) values (44, 'Uri');
insert into City(idCountry, nameCity) values (44, 'Valais');
insert into City(idCountry, nameCity) values (44, 'Vaud');
insert into City(idCountry, nameCity) values (44, 'Zug');
insert into City(idCountry, nameCity) values (44, 'Zürich');
---Estonia
insert into City(idCountry, nameCity) values (45, 'Harju');
insert into City(idCountry, nameCity) values (45, 'Hiiumaa Parish');
insert into City(idCountry, nameCity) values (45, 'Järva');
insert into City(idCountry, nameCity) values (45, 'Jõgeva');
insert into City(idCountry, nameCity) values (45, 'Lääne');
insert into City(idCountry, nameCity) values (45, 'Lääne-Viru');
insert into City(idCountry, nameCity) values (45, 'Pärnu');
insert into City(idCountry, nameCity) values (45, 'Põlva');
insert into City(idCountry, nameCity) values (45, 'Rapla');
insert into City(idCountry, nameCity) values (45, 'Saare');
insert into City(idCountry, nameCity) values (45, 'Tartu');
insert into City(idCountry, nameCity) values (45, 'Valga');
insert into City(idCountry, nameCity) values (45, 'Viljandi');
insert into City(idCountry, nameCity) values (45, 'Võru');
insert into City(idCountry, nameCity) values (45, 'Ida-Viru');
---Montenegro
insert into City(idCountry, nameCity) values (46, 'Andrijevica');
insert into City(idCountry, nameCity) values (46, 'Bar');
insert into City(idCountry, nameCity) values (46, 'Berane');
insert into City(idCountry, nameCity) values (46, 'Bijelo Polje');
insert into City(idCountry, nameCity) values (46, 'Budva');
insert into City(idCountry, nameCity) values (46, 'Cetinje');
insert into City(idCountry, nameCity) values (46, 'Danilovgrad');
insert into City(idCountry, nameCity) values (46, 'Herceg Novi');
insert into City(idCountry, nameCity) values (46, 'Kolašin');
insert into City(idCountry, nameCity) values (46, 'Kotor');
insert into City(idCountry, nameCity) values (46, 'Mojkovac');
insert into City(idCountry, nameCity) values (46, 'Nikšić');
insert into City(idCountry, nameCity) values (46, 'Plav');
insert into City(idCountry, nameCity) values (46, 'Pljevlja');
insert into City(idCountry, nameCity) values (46, 'Plužine');
insert into City(idCountry, nameCity) values (46, 'Podgorica');
insert into City(idCountry, nameCity) values (46, 'Rožaje');
insert into City(idCountry, nameCity) values (46, 'Šavnik');
insert into City(idCountry, nameCity) values (46, 'Tivat');
insert into City(idCountry, nameCity) values (46, 'Ulcinj');
insert into City(idCountry, nameCity) values (46, 'Žabljak');
---Andorra
insert into City(idCountry, nameCity) values (47, 'Andorra la Vieja');
insert into City(idCountry, nameCity) values (47, 'Canillo');
insert into City(idCountry, nameCity) values (47, 'Encamp');
insert into City(idCountry, nameCity) values (47, 'Escaldes-Engordany');
insert into City(idCountry, nameCity) values (47, 'La Massana');
insert into City(idCountry, nameCity) values (47, 'Ordino');
insert into City(idCountry, nameCity) values (47, 'Sant Julià de Lòria');
---Bélgica
insert into City(idCountry, nameCity) values (48, 'Amberes');
insert into City(idCountry, nameCity) values (48, 'Flandes Oriental');
insert into City(idCountry, nameCity) values (48, 'Brabante Flamenco');
insert into City(idCountry, nameCity) values (48, 'Limburgo');
insert into City(idCountry, nameCity) values (48, 'Flandes Occidental');
insert into City(idCountry, nameCity) values (48, 'Henao');
insert into City(idCountry, nameCity) values (48, 'Lieja');
insert into City(idCountry, nameCity) values (48, 'Luxemburgo');
insert into City(idCountry, nameCity) values (48, 'Namur');
insert into City(idCountry, nameCity) values (48, 'Brabante Valón');
---Bulgaria
insert into City(idCountry, nameCity) values (49, 'Blagoevgrad');
insert into City(idCountry, nameCity) values (49, 'Burgas');
insert into City(idCountry, nameCity) values (49, 'Shumen');
insert into City(idCountry, nameCity) values (49, 'Dobrich');
insert into City(idCountry, nameCity) values (49, 'Gabrovo');
insert into City(idCountry, nameCity) values (49, 'Krudzhali');
insert into City(idCountry, nameCity) values (49, 'Haskovo');
insert into City(idCountry, nameCity) values (49, 'Kyustendil');
insert into City(idCountry, nameCity) values (49, 'Lovech');
insert into City(idCountry, nameCity) values (49, 'Montana');
insert into City(idCountry, nameCity) values (49, 'Pazardzhik');
insert into City(idCountry, nameCity) values (49, 'Pernik');
insert into City(idCountry, nameCity) values (49, 'Pleven');
insert into City(idCountry, nameCity) values (49, 'Plovdiv');
insert into City(idCountry, nameCity) values (49, 'Razgrad');
insert into City(idCountry, nameCity) values (49, 'Ruse');
insert into City(idCountry, nameCity) values (49, 'Silistra');
insert into City(idCountry, nameCity) values (49, 'Sliven');
insert into City(idCountry, nameCity) values (49, 'Smolyan');
insert into City(idCountry, nameCity) values (49, 'Sofia');
insert into City(idCountry, nameCity) values (49, 'Sofia-Ciudad');
insert into City(idCountry, nameCity) values (49, 'Stara Zagora');
insert into City(idCountry, nameCity) values (49, 'Targovishte');
insert into City(idCountry, nameCity) values (49, 'Varna');
insert into City(idCountry, nameCity) values (49, 'Veliko Tarnovo');
insert into City(idCountry, nameCity) values (49, 'Vidin');
insert into City(idCountry, nameCity) values (49, 'Vratsa');
insert into City(idCountry, nameCity) values (49, 'Yambol');
---Chequia
insert into City(idCountry, nameCity) values (50, 'Bohemia Central');
insert into City(idCountry, nameCity) values (50, 'Bohemia Meridional');
insert into City(idCountry, nameCity) values (50, 'Hradec Kralove');
insert into City(idCountry, nameCity) values (50, 'Karlovy Vary');
insert into City(idCountry, nameCity) values (50, 'Liberec');
insert into City(idCountry, nameCity) values (50, 'Moravia Meridional');
insert into City(idCountry, nameCity) values (50, 'Moravskoslezský');
insert into City(idCountry, nameCity) values (50, 'Olomouc');
insert into City(idCountry, nameCity) values (50, 'Pardubice');
insert into City(idCountry, nameCity) values (50, 'Pilse');
insert into City(idCountry, nameCity) values (50, 'Praga');
insert into City(idCountry, nameCity) values (50, 'Ústí nad Labem');
insert into City(idCountry, nameCity) values (50, 'Vysočina');
insert into City(idCountry, nameCity) values (50, 'Zlínský');
---Finlandia
insert into City(idCountry, nameCity) values (51, 'Finlandia Meridional');
insert into City(idCountry, nameCity) values (51, 'Finlandia Occidental');
insert into City(idCountry, nameCity) values (51, 'Finlandia Oriental');
insert into City(idCountry, nameCity) values (51, 'Laponia');
insert into City(idCountry, nameCity) values (51, 'Oulu');
---Alemania
insert into City(idCountry, nameCity) values (52, 'Baden-Württemberg');
insert into City(idCountry, nameCity) values (52, 'Bajo Sajonia');
insert into City(idCountry, nameCity) values (52, 'Baviera');
insert into City(idCountry, nameCity) values (52, 'Berlín');
insert into City(idCountry, nameCity) values (52, 'Brandenburgo');
insert into City(idCountry, nameCity) values (52, 'Brema');
insert into City(idCountry, nameCity) values (52, 'Hamburgo');
insert into City(idCountry, nameCity) values (52, 'Hesse');
insert into City(idCountry, nameCity) values (52, 'Mecklenburgo-Pomerania Occidental');
insert into City(idCountry, nameCity) values (52, 'Renania-Westfalia');
insert into City(idCountry, nameCity) values (52, 'Renania-Palatinado');
insert into City(idCountry, nameCity) values (52, 'El Sarre');
insert into City(idCountry, nameCity) values (52, 'Sajonia');
insert into City(idCountry, nameCity) values (52, 'Sajonia-Anhalt');
insert into City(idCountry, nameCity) values (52, 'Schleswig-Holstein');
insert into City(idCountry, nameCity) values (52, 'Turingia');
---Ciudad del Vaticano
insert into City(idCountry, nameCity) values (53, 'Ciudad del Vaticano');
---Islandia
insert into City(idCountry, nameCity) values (54, 'Austurland');
insert into City(idCountry, nameCity) values (54, 'Höfuðborgarsvæði');
insert into City(idCountry, nameCity) values (54, 'Norðurland eystra');
insert into City(idCountry, nameCity) values (54, 'Norðurland vestra');
insert into City(idCountry, nameCity) values (54, 'Suðurland');
insert into City(idCountry, nameCity) values (54, 'Suðurnes');
insert into City(idCountry, nameCity) values (54, 'Vestfirðir');
insert into City(idCountry, nameCity) values (54, 'Vesturland');
---Italia
insert into City(idCountry, nameCity) values (55, 'Abruzzo');
insert into City(idCountry, nameCity) values (55, 'Basilicata');
insert into City(idCountry, nameCity) values (55, 'Calabria');
insert into City(idCountry, nameCity) values (55, 'Campania');
insert into City(idCountry, nameCity) values (55, 'Emilia-Romagna');
insert into City(idCountry, nameCity) values (55, 'Friuli-Venezia Giulia');
insert into City(idCountry, nameCity) values (55, 'Lazio');
insert into City(idCountry, nameCity) values (55, 'Liguria');
insert into City(idCountry, nameCity) values (55, 'Lombardy');
insert into City(idCountry, nameCity) values (55, 'Marche');
insert into City(idCountry, nameCity) values (55, 'Molise');
insert into City(idCountry, nameCity) values (55, 'Umbria');
insert into City(idCountry, nameCity) values (55, 'Piedmont');
insert into City(idCountry, nameCity) values (55, 'Apulia');
insert into City(idCountry, nameCity) values (55, 'Cerdeña');
insert into City(idCountry, nameCity) values (55, 'Sicily');
insert into City(idCountry, nameCity) values (55, 'Tuscany');
insert into City(idCountry, nameCity) values (55, 'Trentino-South Tyrol');
insert into City(idCountry, nameCity) values (55, 'Aosta Valley');
insert into City(idCountry, nameCity) values (55, 'Veneto');
---Liechtenstein
insert into City(idCountry, nameCity) values (56, 'Oberland');
insert into City(idCountry, nameCity) values (56, 'Unterland');
---Luxemburgo
insert into City(idCountry, nameCity) values (57, 'Diekirch');
insert into City(idCountry, nameCity) values (57, 'Grevenmacher');
insert into City(idCountry, nameCity) values (57, 'Luxembourg');
---Malta
insert into City(idCountry, nameCity) values (58, 'Gozo');
insert into City(idCountry, nameCity) values (58, 'Malta');
---Países Bajo
insert into City(idCountry, nameCity) values (59, 'Brabante Septentrional');
insert into City(idCountry, nameCity) values (59, 'Drente');
insert into City(idCountry, nameCity) values (59, 'Flevolanda');
insert into City(idCountry, nameCity) values (59, 'Frisia');
insert into City(idCountry, nameCity) values (59, 'Güeldres');
insert into City(idCountry, nameCity) values (59, 'Groninga');
insert into City(idCountry, nameCity) values (59, 'Holanda Meridional');
insert into City(idCountry, nameCity) values (59, 'Holanda Septentrional');
insert into City(idCountry, nameCity) values (59, 'Limburgo');
insert into City(idCountry, nameCity) values (59, 'Overijssel');
insert into City(idCountry, nameCity) values (59, 'Utrecht');
insert into City(idCountry, nameCity) values (59, 'Zelándia');
---Polonia
insert into City(idCountry, nameCity) values (60, 'Baja Silesia');
insert into City(idCountry, nameCity) values (60, 'Subcarpática');
insert into City(idCountry, nameCity) values (60, 'Cuyavia y Pomerania');
insert into City(idCountry, nameCity) values (60, 'Gran Polonia');
insert into City(idCountry, nameCity) values (60, 'Lublin');
insert into City(idCountry, nameCity) values (60, 'Lubusz');
insert into City(idCountry, nameCity) values (60, 'Łódź');
insert into City(idCountry, nameCity) values (60, 'Mazovia');
insert into City(idCountry, nameCity) values (60, 'Opole');
insert into City(idCountry, nameCity) values (60, 'Pequeña Polonia');
insert into City(idCountry, nameCity) values (60, 'Podlaquia');
insert into City(idCountry, nameCity) values (60, 'Pomerania');
insert into City(idCountry, nameCity) values (60, 'Pomerania Occidental');
insert into City(idCountry, nameCity) values (60, 'Santa Cruz');
insert into City(idCountry, nameCity) values (60, 'Silesia');
insert into City(idCountry, nameCity) values (60, 'Warmia y Mazuria');
---Rumania
insert into City(idCountry, nameCity) values (61, 'Arad');
insert into City(idCountry, nameCity) values (61, 'Alba');
insert into City(idCountry, nameCity) values (61, 'Argeș');
insert into City(idCountry, nameCity) values (61, 'Bacău');
insert into City(idCountry, nameCity) values (61, 'Bihor');
insert into City(idCountry, nameCity) values (61, 'Bistrița-Năsăud');
insert into City(idCountry, nameCity) values (61, 'Botoșani');
insert into City(idCountry, nameCity) values (61, 'Brăila');
insert into City(idCountry, nameCity) values (61, 'Brașov');
insert into City(idCountry, nameCity) values (61, 'București');
insert into City(idCountry, nameCity) values (61, 'Buzău');
insert into City(idCountry, nameCity) values (61, 'Călărași');
insert into City(idCountry, nameCity) values (61, 'Caraș-Severin');
insert into City(idCountry, nameCity) values (61, 'Cluj');
insert into City(idCountry, nameCity) values (61, 'Constanța');
insert into City(idCountry, nameCity) values (61, 'Covasna');
insert into City(idCountry, nameCity) values (61, 'Dâmbovița');
insert into City(idCountry, nameCity) values (61, 'Dolj');
insert into City(idCountry, nameCity) values (61, 'Galați');
insert into City(idCountry, nameCity) values (61, 'Giurgiu');
insert into City(idCountry, nameCity) values (61, 'Gorj');
insert into City(idCountry, nameCity) values (61, 'Harghita');
insert into City(idCountry, nameCity) values (61, 'Hunedoara');
insert into City(idCountry, nameCity) values (61, 'Ialomița');
insert into City(idCountry, nameCity) values (61, 'Iași');
insert into City(idCountry, nameCity) values (61, 'Ilfov');
insert into City(idCountry, nameCity) values (61, 'Maramureș');
insert into City(idCountry, nameCity) values (61, 'Mehedinți');
insert into City(idCountry, nameCity) values (61, 'Mureș');
insert into City(idCountry, nameCity) values (61, 'Neamț');
insert into City(idCountry, nameCity) values (61, 'Olt');
insert into City(idCountry, nameCity) values (61, 'Prahova');
insert into City(idCountry, nameCity) values (61, 'Satu Mare');
insert into City(idCountry, nameCity) values (61, 'Sălaj');
insert into City(idCountry, nameCity) values (61, 'Sibiu');
insert into City(idCountry, nameCity) values (61, 'Suceava');
insert into City(idCountry, nameCity) values (61, 'Teleorman');
insert into City(idCountry, nameCity) values (61, 'Timiș');
insert into City(idCountry, nameCity) values (61, 'Tulcea');
insert into City(idCountry, nameCity) values (61, 'Vâlcea');
insert into City(idCountry, nameCity) values (61, 'Vaslui');
insert into City(idCountry, nameCity) values (61, 'Vrancea');
---San Marino
insert into City(idCountry, nameCity) values (62, 'San Marino');
---Eslovenia
insert into City(idCountry, nameCity) values (63, 'Eslovenia');
---Suecia
insert into City(idCountry, nameCity) values (64, 'Blekinge');
insert into City(idCountry, nameCity) values (64, 'Dalarna');
insert into City(idCountry, nameCity) values (64, 'Gotland');
insert into City(idCountry, nameCity) values (64, 'Gävleborg');
insert into City(idCountry, nameCity) values (64, 'Halland');
insert into City(idCountry, nameCity) values (64, 'Jämtland');
insert into City(idCountry, nameCity) values (64, 'Jönköping');
insert into City(idCountry, nameCity) values (64, 'Kalmar');
insert into City(idCountry, nameCity) values (64, 'Kronoberg');
insert into City(idCountry, nameCity) values (64, 'Norrbotten');
insert into City(idCountry, nameCity) values (64, 'Örebro');
insert into City(idCountry, nameCity) values (64, 'Östergötland');
insert into City(idCountry, nameCity) values (64, 'Skåne');
insert into City(idCountry, nameCity) values (64, 'Södermanland');
insert into City(idCountry, nameCity) values (64, 'Estocolmo');
insert into City(idCountry, nameCity) values (64, 'Upsala');
insert into City(idCountry, nameCity) values (64, 'Värmland');
insert into City(idCountry, nameCity) values (64, 'Västerbotten');
insert into City(idCountry, nameCity) values (64, 'Västernorrland');
insert into City(idCountry, nameCity) values (64, 'Västmanland');
insert into City(idCountry, nameCity) values (64, 'Västra Götaland');
---Inglaterra
insert into City(idCountry, nameCity) values (65, 'East Midlands');
insert into City(idCountry, nameCity) values (65, 'East of England');
insert into City(idCountry, nameCity) values (65, 'London');
insert into City(idCountry, nameCity) values (65, 'North East England');
insert into City(idCountry, nameCity) values (65, 'North West England');
insert into City(idCountry, nameCity) values (65, 'South East England');
insert into City(idCountry, nameCity) values (65, 'South West England');
insert into City(idCountry, nameCity) values (65, 'West Midlands');
insert into City(idCountry, nameCity) values (65, 'Yorkshire and the Humber');
---Gales
insert into City(idCountry, nameCity) values (66, 'Blaenau Gwent');
insert into City(idCountry, nameCity) values (66, 'Bridgend');
insert into City(idCountry, nameCity) values (66, 'Caerphilly');
insert into City(idCountry, nameCity) values (66, 'Cardiff');
insert into City(idCountry, nameCity) values (66, 'Carmarthenshire');
insert into City(idCountry, nameCity) values (66, 'Ceredigion');
insert into City(idCountry, nameCity) values (66, 'Conwy');
insert into City(idCountry, nameCity) values (66, 'Denbighshire');
insert into City(idCountry, nameCity) values (66, 'Flintshire');
insert into City(idCountry, nameCity) values (66, 'Gwynedd');
insert into City(idCountry, nameCity) values (66, 'Isle of Anglesey');
insert into City(idCountry, nameCity) values (66, 'Merthyr Tydfil');
insert into City(idCountry, nameCity) values (66, 'Monmouthshire');
insert into City(idCountry, nameCity) values (66, 'Neath Port Talbot');
insert into City(idCountry, nameCity) values (66, 'Newport');
insert into City(idCountry, nameCity) values (66, 'Pembrokeshire');
insert into City(idCountry, nameCity) values (66, 'Powys');
insert into City(idCountry, nameCity) values (66, 'Rhondda Cynon Taf');
insert into City(idCountry, nameCity) values (66, 'Swansea');
insert into City(idCountry, nameCity) values (66, 'Torfaen');
insert into City(idCountry, nameCity) values (66, 'Vale of Glamorgan');
insert into City(idCountry, nameCity) values (66, 'Wrexham');
---Escocia
insert into City(idCountry, nameCity) values (67, 'Aberdeen City');
insert into City(idCountry, nameCity) values (67, 'Aberdeenshire');
insert into City(idCountry, nameCity) values (67, 'Angus');
insert into City(idCountry, nameCity) values (67, 'Argyll and Bute');
insert into City(idCountry, nameCity) values (67, 'City of Edinburgh');
insert into City(idCountry, nameCity) values (67, 'Clackmannanshire');
insert into City(idCountry, nameCity) values (67, 'Dumfries and Galloway');
insert into City(idCountry, nameCity) values (67, 'Dundee City');
insert into City(idCountry, nameCity) values (67, 'East Ayrshire');
insert into City(idCountry, nameCity) values (67, 'East Dunbartonshire');
insert into City(idCountry, nameCity) values (67, 'East Lothian');
insert into City(idCountry, nameCity) values (67, 'East Renfrewshire');
insert into City(idCountry, nameCity) values (67, 'Falkirk');
insert into City(idCountry, nameCity) values (67, 'Fife');
insert into City(idCountry, nameCity) values (67, 'Glasgow City');
insert into City(idCountry, nameCity) values (67, 'Highland');
insert into City(idCountry, nameCity) values (67, 'Inverclyde');
insert into City(idCountry, nameCity) values (67, 'Midlothian');
insert into City(idCountry, nameCity) values (67, 'Moray');
insert into City(idCountry, nameCity) values (67, 'Na h-Eileanan Siar');
insert into City(idCountry, nameCity) values (67, 'North Ayrshire');
insert into City(idCountry, nameCity) values (67, 'North Lanarkshire');
insert into City(idCountry, nameCity) values (67, 'Orkney Islands');
insert into City(idCountry, nameCity) values (67, 'Perth and Kinross');
insert into City(idCountry, nameCity) values (67, 'Renfrewshire');
insert into City(idCountry, nameCity) values (67, 'Scottish Borders');
insert into City(idCountry, nameCity) values (67, 'Shetland Islands');
insert into City(idCountry, nameCity) values (67, 'South Ayrshire');
insert into City(idCountry, nameCity) values (67, 'South Lanarkshire');
insert into City(idCountry, nameCity) values (67, 'Stirling');
insert into City(idCountry, nameCity) values (67, 'West Dunbartonshire');
insert into City(idCountry, nameCity) values (67, 'West Lothian');
---Serbia
insert into City(idCountry, nameCity) values (68, 'Belgrade');
insert into City(idCountry, nameCity) values (68, 'Vojvodina');
insert into City(idCountry, nameCity) values (68, 'Šumadija and Western Serbia');
insert into City(idCountry, nameCity) values (68, 'South and Eastern Serbia');
insert into City(idCountry, nameCity) values (68, 'Kosovo and Metohija');
COMMIT;
