package LogicClasses;

import Connect.ConnectDB;
import Interface.ParticipantWindow;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Test {
    public static byte[] toBytes(String imagePath) throws IOException {
    FileInputStream fis;
    byte [] image = new byte[1];
            try {
                fis = new FileInputStream(imagePath);
                image = new byte[fis.available()];
                fis.read(image);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ParticipantWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        return image;    
    }

    public static void main(String[] args){
        ConnectDB con = ConnectDB.getObject();
        String adress = "C:\\Users\\josed\\OneDrive\\Escritorio\\Imagenes\\";
        //Canadian
        //con.insertParticipant(1,"Keanu",null,"Reeves",null,"02-09-1964",5,18,"(Keanu Charles Reeves; Beirut, Líbano, 1964) Actor de cine estadounidense. De padre chino-hawaiano y de madre británica, Keanu Reeves creció en Toronto y se trasladó a los 16 años a Los Ángeles para trabajar como actor. De hecho ya antes, durante su estancia en Canadá, había actuado en el Theatre Arts High School.",186,null,adress+"keanu.jpg");
        //American
        try {
        /*con.insertParticipant(1,"Chad",null,"Stahelski",null,"02-08-1968",5,"Chad Stahelski (20 de septiembre de 1968) es un director de cine y doble de riesgo estadounidense, reconocido por dirigir la saga de John Wick.1​2​3​ Stahelski además ofició como doble de Brandon Lee tras el accidente que le costó la vida al actor durante el rodaje de la película The Crow (1994).4​ Ha trabajado como coordinador de acrobacias y director de segunda unidad en varias películas.",185,null,toBytes(adress+"chad.jpg"));
        con.insertParticipant(1,"Tyler",null,"Bates",null,"05-06-1965",5,"Tyler Bates (Los Ángeles, 5 de junio de 1965) es un productor musical y compositor estadounidense de música para cine, televisión y videojuegos. Entre sus trabajos más conocidos están las bandas sonoras de las películas Halloween, John Wick, Guardianes de la Galaxia...",191,null,toBytes(adress+"tylerBates.jpg"));
        //Scotland
        con.insertParticipant(1,"Mikael",null,"Nyqvist",null,"08-11-1960",5,"Nacido en Estocolmo de padre italiano y madre sueca, Nyqvist se crio en un orfanato, de donde fue adoptado y estudió en la Escuela de Arte Dramático de Malmö.2​ Se dio a conocer en la primera temporada de la serie Beck (1997), en el papel de Banck. En la película El clavel negro fue el diplomático y humanitario sueco Harald Edelstam y ganó el Premio Guldbagge como mejor actor masculino en 2003.",178,null,toBytes(adress+"mikael.jpg"));
        //American
        con.insertParticipant(2,"Adrianne",null,"Palicki",null,"06-05-1983",5,"Adrianne Lee Palicki (Toledo, Ohio, 6 de mayo de 1983) es una actriz estadounidense conocida por su papel de Tyra Collette en la serie televisiva Friday Night Lights, como Bobbi Morse/Mockingbird en la serie Agents of S.H.I.E.L.D. de la cadena ABC y por su papel de Jessica Moore en la serie Supernatural.",180,null,toBytes(adress+"adrianne.jpg"));
        //English
        con.insertParticipant(1,"Ian","David","McShane",null,"29-09-1942",5,"Ian David McShane (Blackburn, Inglaterra; 29 de septiembre de 1942) es un actor británico. A pesar de que ha protagonizado varias películas, es por sus papeles en televisión por los que es más conocido, comenzando por la serie de la BBC Lovejoy (1986-1994) y el wéstern de la HBO Deadwood (2004-2006), con la que obtuvo un Globo de Oro.",170,null,toBytes(adress+"ianMcShane.jpg"));
        //Canadian
        con.insertParticipant(1,"Denis",null,"Villeneuve",null,"03-10-1967",5,"Denis Villeneuve (Trois-Rivières, Quebec, 3 de octubre de 1967) es un guionista y director de cine canadiense. Fue nominado a un premio Óscar en la categoría de mejor dirección por su película La llegada (2016), y ha ganado tres premios Genie como mejor director por sus largometrajes Maelström (2000), Polytechnique (2009) e Incendies (2010).",182,null,toBytes(adress+"villeneuve.jpg"));
        //German
        con.insertParticipant(1,"Hans",null,"Zimmer",null,"12-09-1957",5,"Hans Florian Zimmer (Fráncfort, 12 de septiembre de 1957) es un compositor de bandas sonoras alemán,1​ que se caracteriza por la integración de música electrónica y arreglos sinfónico-orquestales. Ha sido acreedor a reconocimientos cinematográficos como los Globos de oro, BAFTA, Emmy, Saturn, Grammy, además de dos Óscar de la Academia por su trabajo en El rey león (1994) y Dune (2021), premios a los que ha sido nominado en otras 10 ocasiones desde 1988 con Rain man.",178,null,toBytes(adress+"hansZimmer.jpg"));
        */
        con.insertParticipant(2, "Jennifer", "Shrader", "Lawrence", null, "15/08/90", 448, "Es una actriz y productora de cine estadounidense. La actriz mejor pagada del mundo en 2015 y 2016, sus películas han recaudado más de $6 mil millones en todo el mundo hasta la fecha. Apareció en la lista de las 100 personas más influyentes del mundo de Time en 2013 y en la lista Forbes Celebrity 100 de 2013 a 2016.", 175, "Ganó el Óscar a la mejor actriz por su participanciónen Silver Linings Playbook con su papel como Tiffany Maxell",toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(2, "Scarlett", "Ingrid", "Johansson", null, "22/11/84", 463, "Es una actriz estadounidense, que también se ha desempeñado ocasionalmente como cantante, productora, modelo y empresaria. Establecida como la actriz mejor remunerada de la industria en 2018 y 2019, figuró en múltiples ocasiones en las listas anuales de Forbes, además de ser citada por la revista Time como una de las celebridades más influyentes del mundo.", 160, "Ha recibido múltiples premios y nominaciones, incluyendo un Premio de la Academia Británica de Cine y un Premio Tony. Además, ha sido nominada para dos Premios Óscar, cinco Globos de Oro y tres de Premios de la Academia Británica de Cine adicionales.", toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Dwayne", "Douglas", "Johnson", null, "02/05/72", 431, "Se desempeñó como luchador profesional para WWE hasta su retirada oficial en 2019,2¿ aunque regresó en 2023 a tiempo parcial. Como actor, ha participado en una gran diversidad de películas en bastantes de ellas, siendo su papel como Luke Hobbs en la franquicia The Fast and the Furious uno de los más reconocidos, así como Black Adam para su cinta independiente Black Adam (2022), perteneciente al Universo extendido de DC.", 196, "Johnson asistió a la Convención Nacional Demócrata de 2000,30¿ como parte de la campaña no partidista de la WWE Smackdown Your Vote, cuyo objetivo era influir en los jóvenes para que votaran. También tuvo un papel de orador en la Convención Nacional Republicana de 2000 ese mismo año.", toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Keanu", "Charles", "Reeves", null, "02/09/64", 1131, "Keanu Charles Reeves nació en Beirut el 2 de septiembre de 1964, es hijo de Patricia Taylor, diseñadora de vestuario y artista, y Samuel Nowlin Reeves, Jr.7¿ Su madre es inglesa, oriunda de Essex.8¿ Su padre, un estadounidense de Hawái, es de ascendencia china, hawaiana, inglesa, irlandesa y portuguesa. Reeves ha dicho: 'Mi abuela es china y hawaiana, así que estuve cerca del arte, los muebles y la cocina chinas a medida que crecía'.", 186, "Reeves comenzó su carrera como actor a la edad de nueve años, apareciendo en una producción teatral de Damn Yankees. A los 15 años, interpretó a Mercutio en una producción teatral de Romeo y Julieta en el Teatro Leah Posluns.", toBytes(adress+"hansZimmer.jpg"));

        con.insertParticipant(1, "Chad", null, "Stahelski", null, "02/08/68", 452, "Chad Stahelski (20 de septiembre de 1968) es un director de cine y doble de riesgo estadounidense, reconocido por dirigir la saga de John Wick.1¿2¿3¿ Stahelski además ofició como doble de Brandon Lee tras el accidente que le costó la vida al actor durante el rodaje de la película The Crow (1994). Ha trabajado como coordinador de acrobacias y director de segunda unidad en varias películas.", 185, "Ha trabajado como coordinador de acrobacias y director de segunda unidad en varias películas.", toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Simon", "Lucas", "Baker", null, "30/07/69", 1132, "Es un actor australiano de cine y televisión. Ha sido la estrella de la serie de televisión El mentalista de la CBS, principalmente como actor, aunque también ha dirigido cinco episodios.", 178, "Ha sido rostro principal de la marca Longines - firma de relojes de lujo (2008 hasta el presente)", toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(2, "Robin", null, "Tunney", null, "19/06/72", 444, "Es una actriz estadounidense de televisión y cine, conocida principalmente por su papel de Teresa Lisbon en la serie de televisión El mentalista.", 162, "Tunney nació en Chicago (Illinois) y creció en el sur del estado. Durante su primer año de preparatoria asistió al St. Ignatius College Prep (Colegio Preparatorio de San Ignacio), un colegio católico en Chicago. Estudió interpretación en la Chicago Academy for the Arts.", toBytes(adress+"hansZimmer.jpg"));
        //con.insertParticipant(1, "Jorge", null, "Mena", null, "10/05/85", 930, Sin biografía 188 Sin trivia
        con.insertParticipant(2, "Adrianne", null, "Palicki", null, "06/05/83", 5, "Adrianne Lee Palicki (Toledo, Ohio, 6 de mayo de 1983) es una actriz estadounidense conocida por su papel de Tyra Collette en la serie televisiva Friday Night Lights, como Bobbi Morse/Mockingbird en la serie Agents of S.H.I.E.L.D. de la cadena ABC y por su papel de Jessica Moore en la serie Supernatural.", 180, null, toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Tyler", null, "Bates", null, "05/06/65", 5, "Tyler Bates (Los Ángeles, 5 de junio de 1965) es un productor musical y compositor estadounidense de música para cine, televisión y videojuegos. Entre sus trabajos más conocidos están las bandas sonoras de las películas Halloween, John Wick, Guardianes de la Galaxia...", 191, null, toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Mikae", null, "Nyqvist", null, "08/11/60", 5, "Nacido en Estocolmo de padre italiano y madre sueca, Nyqvist se crio en un orfanato, de donde fue adoptado y estudió en la Escuela de Arte Dramático de Malmö.2¿ Se dio a conocer en la primera temporada de la serie Beck (1997), en el papel de Banck. En la película El clavel negro fue el diplomático y humanitario sueco Harald Edelstam y ganó el Premio Guldbagge como mejor actor masculino en 2003.", 178, null, toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Ian", "David", "McShane", null, "29/09/42", 5, "Ian David McShane (Blackburn, Inglaterra; 29 de septiembre de 1942) es un actor británico. A pesar de que ha protagonizado varias películas, es por sus papeles en televisión por los que es más conocido, comenzando por la serie de la BBC Lovejoy (1986-1994) y el wéstern de la HBO Deadwood (2004-2006), con la que obtuvo un Globo de Oro.", 170, null, toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Denis", null, "Villeneuve", null, "03/10/67", 5, "Denis Villeneuve (Trois-Rivières, Quebec, 3 de octubre de 1967) es un guionista y director de cine canadiense. Fue nominado a un premio Óscar en la categoría de mejor dirección por su película La llegada (2016), y ha ganado tres premios Genie como mejor director por sus largometrajes Maelström (2000), Polytechnique (2009) e Incendies (2010).", 182, null, toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Hans", null, "Zimmer", null, "12/09/57", 921, "Hans Florian Zimmer (Fráncfort, 12 de septiembre de 1957) es un compositor de bandas sonoras alemán,1¿ que se caracteriza por la integración de música electrónica y arreglos sinfónico-orquestales. Ha sido acreedor a reconocimientos cinematográficos como los Globos de oro, BAFTA, Emmy, Saturn, Grammy, además de dos Óscar de la Academia por su trabajo en El rey león (1994) y Dune (2021), premios a los que ha sido nominado en otras 10 ocasiones desde 1988 con Rain man.", 178, "En la actualidad es considerado uno de los compositores más sobresalientes de Hollywood, apodado por gran parte de la crítica como «el omnipresente Zimmer» por sus numerosas apariciones.", toBytes(adress+"hansZimmer.jpg"));
        con.insertParticipant(1, "Ryan", "Rodney", "Reynolds", null, "23/10/76", 45, "Ryan Rodney Reynolds (Vancouver, 23 de octubre de 1976) es un actor, actor de voz, comediante, guionista y productor de cine canadoestadounidense.El mayor éxito comercial de Reynolds se produjo con las películas Deadpool (2016) y Deadpool 2 (2018) de las productoras 20th Century Studios-Marvel Entertainment, en las que interpretó al personaje principal.", 188, "Reynolds fue nombrado el hombre vivo más sexy de People en 2010 y recibió una estrella en el Paseo de la fama de Hollywood en 2017", toBytes(adress+"hansZimmer.jpg"));
        
        
        
        con.insertProduct(1,2021,"Dune",156,"https://www.youtube.com/watch?v=kPjOcWHVNGo","\"Dune\", el periplo de un héroe mítico y con una enorme carga emocional, cuenta la historia de Paul Atreides. Se trata de un joven brillante y de gran talento con un destino grandioso que no comprende todavía y que deberá viajar al planeta más peligroso del universo para asegurar el futuro de su familia y de su pueblo. Mientras las fuerzas del mal se enfrentan por uno de los recursos más excepcionales del planeta que tiene el poder de desbloquear todo el potencial de la humanidad, solo los que logren dominar sus miedos podrán sobrevivir.",4);
        con.insertProduct(1,2014,"John Wick",101,"https://www.youtube.com/watch?v=C0BMx-qxsP4&embeds_referring_euri=https%3A%2F%2Fwww.bing.com%2F&embeds_referring_origin=https%3A%2F%2Fwww.bing.com&source_ve_path=Mjg2NjY&feature=emb_logo","John Wick está de luto por la muerte de su esposa, Helen, a causa de una enfermedad. Para ayudarle a sobrellevarlo, ella le regala un cachorro de beagle. Pocos días después, Wick es abordado en una gasolinera a las afueras de Nueva York por un grupo de gánsteres rusos, liderados por Iosef, que no consiguen intimidar a Wick para que les venda su Mustang Boss 429 de 1969. Esa noche, los hombres irrumpen en la casa de Wick, lo asaltan y matan al cachorro antes de robar el coche.",6);
        con.insertProduct(1,2012,"Los Juegos del Hambre",142,"https://www.youtube.com/watch?v=PbA63a7H0bo","Cada distrito se ve obligado a enviar anualmente un chico y una chica entre los doce y los dieciocho años para que participen en los Hunger Games, unos juegos que son transmitidos en directo por la televisión. Se trata de una lucha a muerte, en la que sólo puede haber un superviviente.",5);
        con.insertProduct(1,2019,"Midsommar",148,"https://www.youtube.com/watch?v=fcylOJ0twFw","Midsommar es una película de terror y drama dirigida por Ari Aster, estrenada en 2019. La historia sigue a Dani Ardor, una estudiante de psicología que está traumatizada por el suicidio de su hermana y el asesinato de sus padres. Este trágico incidente afecta profundamente su relación con su novio Christian Hughes, un estudiante de antropología.",8);
        con.insertProduct(2,2008,"Breaking Bad",5,"https://www.youtube.com/watch?v=mXd1zTwcQ18","Albuquerque, ciudad del estado de Nuevo México (Estados Unidos), un profesor de química de instituto llamado Walter White (Bryan Cranston) descubre que padece un cáncer incurable.\n" +"A raíz de esta noticia, y temiendo por la economía de su familia, decide aliarse con un antiguo alumno, Jesse Pinkman (Aaron Paul), para producir y vender metanfetamina.",15);
        con.insertProduct(2,2005,"The Office",9,"https://www.youtube.com/watch?v=tNcDHWpselE","El iluso jefe Michael intenta encauzar el descontento de su empleados en la empresa papelera Dunder Mifflin a través de continuas debilidades y percances.",15);
        con.insertProduct(3,1999,"Caminando Entre Dinosaurios",1,"https://www.youtube.com/watch?v=qj9qCA91NqA","Los episodios se desarrollan como los documentales comunes sobre vida salvaje, tomando un animal como protagonista y mostrando su interacción diaria con el medio, sus presas, depredadores y otros seres vivos que lo rodean.",8);
        con.insertProduct(1,2012,"Los Vengadores",143,"https://www.youtube.com/watch?v=HQIiYqOVTWo","Cuando un enemigo inesperado surge como una gran amenaza para la seguridad mundial, Nick Fury, director de la Agencia SHIELD, decide reclutar a un equipo para salvar al mundo de un desastre casi seguro. Adaptación del cómic de Marvel \"Los Vengadores\", el legendario grupo de superhéroes formado por Ironman, Hulk, Thor y el Capitán América entre otros.",5);
        con.insertProduct(1,1977,"Star Wars: Una Nueva Esperanza",121, "https://www.youtube.com/watch?v=vZ734NWnAHA", "En medio de la guerra galáctica, la Alianza Rebelde ha robado los planos de la poderosa estación espacial Estrella de la Muerte, con los que espera obtener ventaja en la guerra. Los planos son transmitidos a la Tantive IV, una nave diplomática al servicio de la Princesa Leia del planeta Alderaan, sin embargo la transmisión es interceptada por el Imperio Galáctico, dando alcance a la Tantive IV. De forma inmediata, las tropas imperiales toman el mando de la nave, con Darth Vader a la cabeza.",7);
        con.insertProduct(1,2023,"Oppenheimer ",180,"https://www.youtube.com/watch?v=uYPbbksJxIg","En 1926, el estudiante en doctorado de 22 años J. Robert Oppenheimer sufre de nostalgia y ansiedad mientras estudia con el físico experimental Patrick Blackett en el Laboratorio Cavendish de la Universidad de Cambridge. Oppenheimer, molesto con Blackett, toma represalias dejándole una manzana envenenada, evitando posteriormente por poco que el científico visitante Niels Bohr se la coma.",5);
        con.insertProduct(1,2001,"Rápido y Furioso",106,"https://www.youtube.com/watch?v=2TAOizOnNPo","El policía de Los Ángeles, Brian O'Conner, debe decidir dónde está realmente su lealtad cuando se enamore del mundo de las carreras callejeras al que ha sido enviado de incógnito para destruir.",7);
        con.insertProduct(1,2008,"Kung Fu Panda",92,"https://www.youtube.com/watch?v=NRc-ze7Wrxw","En el Valle de la Paz, una tierra de la Antigua China habitada por animales antropomórficos, Po, un panda que come fideos, es fanático del kung fu e idolatra a los Cinco Furiosos: Mantis, Mono, Víbora, Grulla y Tigresa, un grupo de maestros de kung fu entrenados por el Maestro Shifu.",5);
        con.insertProduct(1,2014,"Whiplash",106,"https://www.youtube.com/watch?v=khLbT8CDGlQ","La historia versa sobre Andrew (Teller), un joven baterista que ha sido aceptado en la Escuela de Música más importante de Estados Unidos. Su vida cambia cuando Fletcher (J.K. Simmons) lo escucha tocar y lo invita a formar parte de su banda estudiantil de jazz. Como se trata de un grupo ya avanzado, la presión para ser el mejor se incrementa hasta llevar al límite a Andrew.",5);
        con.insertProduct(1,2020,"Soul",100,"https://www.youtube.com/watch?v=8o_XbDKyBDg","La historia principal gira en torno a un hombre llamado Joe Gardner, un profesor de música de una escuela secundaria que vive en la ciudad de Nueva York, el cual se siente atrapado en su infeliz vida e insatisfecho en su trabajo actual.",7);
        con.insertProduct(1,2015,"Jurassic World",124,"https://www.youtube.com/watch?v=RFinNxS5KN4","Veintidós años después de lo ocurrido en Jurassic Park, la isla Nublar ha sido transformada en un enorme parque temático, Jurassic Wold, con versiones «domesticadas» de algunos de los dinosaurios más conocidos.",5);
     
        
        /*Añadidos*/
        con.insertProduct(1, 2021, "Alerta Roja", 158, "https://www.imdb.com/video/vi612877081/?playlistId=tt7991608&ref_=tt_ov_vi", "Un agente de la Interpol le sigue la pista a la ladrona de arte más buscada del mundo.", 9);
        con.insertProduct(2, 2008, "El mentalista", 151, "https://www.imdb.com/video/vi4252282393/?playlistId=tt1196946&ref_=ext_shr_lnk", "Patrick Jane (Simon Baker) es un psíquico que se gana la vida apareciendo en programas de televisión. Su vida cambia cuando en un programa de TV calumnia a un asesino en serie conocido como Red John y este en venganza, asesina cruelmente a su esposa e hija. A partir de entonces, Patrick decide no ser más un psíquico sino utilizar sus dotes excepcionales de observación y verbosidad, combinadas con sus habilidades de hipnosis, prestidigitación e ilusionismo, para colaborar como asesor en el Buró de Investigación de California", 10);
        con.insertProduct(2, 2022, "Halo", 17, "https://youtu.be/5mcO5WiBmxM?feature=shared", "Halo seguirá un conflicto épico en el siglo 26 entre la humanidad y una amenaza alienígena conocida como el Covenant. Halo entretejerá historias personales profundamente dibujadas con acción, aventura y una visión ricamente imaginada del futuro", 7);
        con.insertProduct(1, 2016, "Deadpool", 148, "https://youtu.be/0JnRdfiUMa8?feature=sharedQ", "Un mercenario de lengua rápida y sentido del humor mórbido es sometido a una operación clandestina que le deja con poderes de curación acelerada y en búsqueda de venganza", 5);
        con.insertProduct(1, 2021, "Matrix", 150, "https://youtu.be/9ix7TUGVYIo?feature=shared", "Un hacker informático descubre a través de misteriosos rebeldes la verdadera naturaleza de su realidad y su papel en la guerra contra sus controladores.", 10);
        //con.insertProduct();
        
        } catch (Exception e){
            System.out.println(""+ e.getMessage());
        }
    }
}
