Begin
    pkgBasic.insertNationality('Argentino');
    pkgBasic.insertNationality('Boliviano');
    pkgBasic.insertNationality('Canadiense');
    pkgBasic.insertNationality('Colombiano');
    pkgBasic.insertNationality('Cubano');
    pkgBasic.insertNationality('Ecuatoriano');
    pkgBasic.insertNationality('Guatemalteco');
    pkgBasic.insertNationality('Haitiano');
    pkgBasic.insertNationality('Jamaiquino');
    pkgBasic.insertNationality('Nicaragüense');
    
    pkgBasic.insertNationality('Paraguayo');
    pkgBasic.insertNationality('Surinamés');
    pkgBasic.insertNationality('Uruguayo');
    pkgBasic.insertNationality('Beliceño');
    pkgBasic.insertNationality('Brasileño');
    pkgBasic.insertNationality('Chileno');
    pkgBasic.insertNationality('Dominicano');
    pkgBasic.insertNationality('Salvadoreño');
    pkgBasic.insertNationality('Guyanés');
    
    pkgBasic.insertNationality('Hondureño');
    pkgBasic.insertNationality('Mexicano');
    pkgBasic.insertNationality('Panameño');
    pkgBasic.insertNationality('Peruano');
    pkgBasic.insertNationality('Estadounidense');
    pkgBasic.insertNationality('Venezolano');
    pkgBasic.insertNationality('Albanés');
    pkgBasic.insertNationality('Austriaco');
    pkgBasic.insertNationality('Bosnio');
    pkgBasic.insertNationality('Croata');
    
    pkgBasic.insertNationality('Danés');
    pkgBasic.insertNationality('Francés');
    pkgBasic.insertNationality('Griego');
    pkgBasic.insertNationality('Húngaro');
    pkgBasic.insertNationality('Irlandés');
    pkgBasic.insertNationality('Letón');
    pkgBasic.insertNationality('Lituano');
    pkgBasic.insertNationality('Macedónio');
    pkgBasic.insertNationality('Monegasco');
    pkgBasic.insertNationality('Noruego');
    
    pkgBasic.insertNationality('Portugués');
    pkgBasic.insertNationality('Ruso');
    pkgBasic.insertNationality('Eslovaco');
    pkgBasic.insertNationality('Español');
    pkgBasic.insertNationality('Suizo');
    pkgBasic.insertNationality('Estonio');
    pkgBasic.insertNationality('Montenegrino');
    pkgBasic.insertNationality('Andorrano');
    pkgBasic.insertNationality('Belga');
    pkgBasic.insertNationality('Búlgaro');
    
    pkgBasic.insertNationality('Checo');
    pkgBasic.insertNationality('Finlandés');
    pkgBasic.insertNationality('Alemán');
    pkgBasic.insertNationality('Vaticano');
    pkgBasic.insertNationality('Islandés');
    pkgBasic.insertNationality('Italiano');
    pkgBasic.insertNationality('Liechtensteiniano');
    pkgBasic.insertNationality('Luxemburgués');
    pkgBasic.insertNationality('Maltés');
    pkgBasic.insertNationality('Neerlandés');
    
    pkgBasic.insertNationality('Polaco');
    pkgBasic.insertNationality('Rumano');
    pkgBasic.insertNationality('Sanmarinense');
    pkgBasic.insertNationality('Esloveno');
    pkgBasic.insertNationality('Sueco');
    pkgBasic.insertNationality('Inglés');
    pkgBasic.insertNationality('Galés');
    pkgBasic.insertNationality('Escocés');
    pkgBasic.insertNationality('Serbio');
    pkgBasic.insertNationality('Costarricense');
    
    pkgBasic.insertNationality('Antiguano');
    pkgBasic.insertNationality('Bahameño');
    pkgBasic.insertNationality('Barbadense');
    pkgBasic.insertNationality('Dominiqués');
    pkgBasic.insertNationality('Granadino');
    pkgBasic.insertNationality('Sancristobaleño');
    pkgBasic.insertNationality('Sanvicentino');
    pkgBasic.insertNationality('Santalucense');
    pkgBasic.insertNationality('Trinitense');
    pkgBasic.insertNationality('Turco');
    
    pkgBasic.insertNationality('Bielorruso');
    pkgBasic.insertNationality('Chipriota');
    pkgBasic.insertNationality('Georgiano');
    pkgBasic.insertNationality('Moldavo');
    pkgBasic.insertNationality('Ucraniano');
    pkgBasic.insertNationality('Afgano');
    pkgBasic.insertNationality('Saudí');
    pkgBasic.insertNationality('Armenio');
    pkgBasic.insertNationality('Azerbaiyano');
    pkgBasic.insertNationality('Bangladesí');
    
    pkgBasic.insertNationality('Bareiní');
    pkgBasic.insertNationality('Birmano');
    pkgBasic.insertNationality('Bruneano');
    pkgBasic.insertNationality('Buranés');
    pkgBasic.insertNationality('Camboyano');
    pkgBasic.insertNationality('Catarí');
    pkgBasic.insertNationality('Chino');
    pkgBasic.insertNationality('Norcoreano');
    pkgBasic.insertNationality('Emiratí');
    pkgBasic.insertNationality('Filipino');
    
    pkgBasic.insertNationality('Indio');
    pkgBasic.insertNationality('Indonés');
    pkgBasic.insertNationality('Iraquí');
    pkgBasic.insertNationality('Iraní');
    pkgBasic.insertNationality('Israelí');
    pkgBasic.insertNationality('Japonés');
    pkgBasic.insertNationality('Jordano');
    pkgBasic.insertNationality('Kazajo');
    pkgBasic.insertNationality('Kirguís');
    pkgBasic.insertNationality('Kuwaití');
    
    pkgBasic.insertNationality('Laosiano');
    pkgBasic.insertNationality('Libanés');
    pkgBasic.insertNationality('Malasio');
    pkgBasic.insertNationality('Maldivo');
    pkgBasic.insertNationality('Mongol');
    pkgBasic.insertNationality('Nepalí');
    pkgBasic.insertNationality('Omaní');
    pkgBasic.insertNationality('Pakistaní');
    pkgBasic.insertNationality('Singapurense');
    pkgBasic.insertNationality('Sirio');
    
    pkgBasic.insertNationality('Esrilanqués');
    pkgBasic.insertNationality('Tailandés');
    pkgBasic.insertNationality('Tayiko');
    pkgBasic.insertNationality('Timorense');
    pkgBasic.insertNationality('Turkmeno');
    pkgBasic.insertNationality('Uzbeko');
    pkgBasic.insertNationality('Vietnamita');
    pkgBasic.insertNationality('Yemení');
    pkgBasic.insertNationality('Australiano');
    pkgBasic.insertNationality('Fiyiano');
    
    pkgBasic.insertNationality('Marshalés');
    pkgBasic.insertNationality('Salomonense');
    pkgBasic.insertNationality('Kiribatiano');
    pkgBasic.insertNationality('Micronesio');
    pkgBasic.insertNationality('Nauruano');
    pkgBasic.insertNationality('Neozelandés');
    pkgBasic.insertNationality('Palauano');
    pkgBasic.insertNationality('Papú');
    pkgBasic.insertNationality('Samoano');
    pkgBasic.insertNationality('Togano');
    
    pkgBasic.insertNationality('Tuvaluano');
    pkgBasic.insertNationality('Vanuatuense');
    pkgBasic.insertNationality('Angoleño');
    pkgBasic.insertNationality('Argelino');
    pkgBasic.insertNationality('Beninés');
    pkgBasic.insertNationality('Botsuano');
    pkgBasic.insertNationality('Burkinés');
    pkgBasic.insertNationality('Burundés');
    pkgBasic.insertNationality('Caboverdiano');
    pkgBasic.insertNationality('Camerunés');
    
    pkgBasic.insertNationality('Chadiano');
    pkgBasic.insertNationality('Comorense');
    pkgBasic.insertNationality('Marfileño');
    pkgBasic.insertNationality('Egipcio');
    pkgBasic.insertNationality('Eritreo');
    pkgBasic.insertNationality('Etíope');
    pkgBasic.insertNationality('Gabonés');
    pkgBasic.insertNationality('Gambiano');
    pkgBasic.insertNationality('Ghanés');
    pkgBasic.insertNationality('Guineano');
    
    pkgBasic.insertNationality('Ecuatoguineano');
    pkgBasic.insertNationality('Keniano');
    pkgBasic.insertNationality('Lesotense');
    pkgBasic.insertNationality('Liberiano');
    pkgBasic.insertNationality('Libio');
    pkgBasic.insertNationality('Malgache');
    pkgBasic.insertNationality('Malauí');
    pkgBasic.insertNationality('Maliense');
    pkgBasic.insertNationality('Marroquí');
    pkgBasic.insertNationality('Mauriciano');
    
    pkgBasic.insertNationality('Mauritano');
    pkgBasic.insertNationality('Mozambiqueño');
    pkgBasic.insertNationality('Namibio');
    pkgBasic.insertNationality('Nigerino');
    pkgBasic.insertNationality('Nigeriano');
    pkgBasic.insertNationality('Centroafricano');
    pkgBasic.insertNationality('Congoleño');
    pkgBasic.insertNationality('Ruandés');
    pkgBasic.insertNationality('Santotomense');
    pkgBasic.insertNationality('Senegalés');
    
    pkgBasic.insertNationality('Seychelense');
    pkgBasic.insertNationality('Sierraleonés');
    pkgBasic.insertNationality('Somalí');
    pkgBasic.insertNationality('Suazi');
    
    pkgBasic.insertNationality('Sudafricano');
    pkgBasic.insertNationality('Sudanés');
    pkgBasic.insertNationality('Sursudanés');
    pkgBasic.insertNationality('Tanzano');
    
    pkgBasic.insertNationality('Togolés');
    pkgBasic.insertNationality('Tunecino');
    pkgBasic.insertNationality('Ugandés');
    pkgBasic.insertNationality('Yibutiano');
    pkgBasic.insertNationality('Zambiano');
    pkgBasic.insertNationality('Zimbabuense');
END;
