/***********************Creation of sequences for all tables*******************/
CREATE SEQUENCE s_sex
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_nationality
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_country
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_city
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_person
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_payment
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_product
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_partXprodu
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_catalog
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_platform
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_review
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_commentary
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000
NOCACHE
NOCYCLE;
