/***********************Creation of sequences for all tables*******************/
CREATE SEQUENCE s_sex
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_binnacle
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_photo
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_identification
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_typeofproduct
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_typeofparticipant
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_nationality
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_country
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_city
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_person
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_payment
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_product
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_partXprodu
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_catalog
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_platform
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_review
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_commentary
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;

CREATE SEQUENCE s_relative
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000000
NOCACHE
NOCYCLE;
